apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: {{ .Values.namespace | default "sense" }}
data:
  # {env}.config.yaml: |
  #    content
  {{ .Values.configmap.common | indent 2 }}
---
