{{- if .Values.cronJob.enabled -}}
{{- range .Values.cronJob.jobs }}
{{- $rangeItem := . -}}
{{- with $ }}
{{- if not $rangeItem.disabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $rangeItem.name }}
  namespace: {{ .Values.namespace | default "sense" }}
spec:
  schedule: {{ $rangeItem.schedule }}
  concurrencyPolicy: {{ $rangeItem.concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ $rangeItem.containerName }}
              image: "{{ .Values.image.repository }}{{ $rangeItem.imageName }}:{{ .Values.image.tag | default "latest" }}"
              resources:
                {{- toYaml $rangeItem.resources | nindent 16 }}
              args:
              {{- if $rangeItem.containerArgs -}}
              {{- range $rangeItem.containerArgs }}
                - {{ toYaml . | trim }}
              {{- end }}
              {{- end }}
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}