{{- range concat .Values.secrets.commons .Values.secrets.services }}
{{- if .secretKey }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace | default "sense" }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-aws-secretstore
    kind: ClusterSecretStore
  target:
    name: {{ .name }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: {{ .key }}
      remoteRef:
        key: {{ .secretKey }}
---
{{- end }}
{{- end }}
