provisionDataStore:
  cassandra: false

storage:
  type: elasticsearch
  elasticsearch:
    host: vpc-qa-sdx-es-nmfy2skqvy27bdipvtlqspa4cy.ap-southeast-1.es.amazonaws.com   
    port: 443
    scheme: https
    user:
    usePassword: false
    indexPrefix: tracing-qa

collector:
  service:
    zipkin:
      port: 9441
  resources:
    limits:
      memory: 128Mi
      cpu: 0.1

query:
  basePath: /jaeger
  resources:
    limits:
      memory: 128Mi
      cpu: 0.1
agent:
  resources:
    limits:
      memory: 128Mi
      cpu: 0.1
esIndexCleaner:
  enabled: true
  numberOfDays: 7