helmBinary: {{ requiredEnv "HELM_BINARY" }}

environments:
  dev:
    values:
      - ./values.yaml
      - ../../dev/global.yaml.gotmpl
      - ../../dev/ingress-controller/values.yaml
  qa:
    values:
      - ./values.yaml
      - ../../qa/global.yaml.gotmpl
      - ../../qa/ingress-controller/values.yaml

repositories:
  - name: ingress-controller
    url: s3://sdx-eks-artifacts/charts/ingress-controller
  - name: aws-load-balancer-controller
    url: https://aws.github.io/eks-charts
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

missingFileHandler: Error

releases:
  - name: ingress-controller
    namespace: ingress-controller
    createNamespace: true
    chart: ingress-controller/ingress-controller
    version: {{ .Values.chartVer | quote }}
    missingFileHandler: Warn
    values:
      - ./values.yaml
      - ./values.yaml.gotmpl
      - ../../{{ .Environment.Name }}/ingress-controller/values.yaml
      - ../../{{ .Environment.Name }}/ingress-controller/values.yaml.gotmpl
      - ../../{{ .Environment.Name }}/ingress-controller/values.external-alb-default.yaml
      - ../../{{ .Environment.Name }}/ingress-controller/values.internal-alb-default.yaml
    hooks:
      - events: [ "presync" ]
        showlogs: true
        command: "sleep"
        args:
          - "45"
    needs:
    {{- if .Values.external.alb.default.enabled }}
    - external-alb-default
    {{- end }}
    {{- if .Values.external.nlb.default.enabled }}
    - external-nlb-default
    {{- end }}
    {{- if .Values.internal.alb.default.enabled }}
    - internal-alb-default
    {{- end }}
    {{- if .Values.internal.nlb.default.enabled }}
    - internal-nlb-default
    {{- end }}

  - name: aws-load-balancer-controller
    namespace: ingress-controller
    createNamespace: true
    chart: aws-load-balancer-controller/aws-load-balancer-controller
    version: 1.4.2
    missingFileHandler: Warn
    disableValidationOnInstall: true # CRD
    values:
      - ./values.aws-load-balancer-controller.yaml
      - ./values.aws-load-balancer-controller.yaml.gotmpl
      - ../../{{ .Environment.Name }}/ingress-controller/values.aws-load-balancer-controller.yaml
      - ../../{{ .Environment.Name }}/ingress-controller/values.aws-load-balancer-controller.yaml.gotmpl
    hooks:
      - events: [ "presync" ]
        showlogs: true
        command: "./scripts/awslbcontroller-pre.sh"
        args:
          - "-a"
          - "{{`{{ .Values.accountId }}`}}"
          - "-e"
          - "{{`{{ .Environment.Name }}`}}"
          - "-c"
          - "{{`{{ .Values.clusterName }}`}}"
          - "-n"
          - "{{`{{ .Values.namespace }}`}}"

  - name: external-alb-default
    namespace: ingress-controller
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    version: 4.2.0
    condition: external-alb-default.enabled
    missingFileHandler: Warn
    values:
      - ./values.external-alb-default.yaml
      - ../../{{ .Environment.Name }}/ingress-controller/values.external-alb-default.yaml

  - name: external-nlb-default
    namespace: ingress-controller
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    version: 4.2.0
    condition: external-nlb-default.enabled
    missingFileHandler: Warn
    values:
      - ./values.external-nlb-default.yaml
      - ../../{{ .Environment.Name }}/ingress-controller/values.external-nlb-default.yaml

  - name: internal-alb-default
    namespace: ingress-controller
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    version: 4.2.0
    condition: internal-alb-default.enabled
    missingFileHandler: Warn
    values:
      - ./values.internal-alb-default.yaml
      - ../../{{ .Environment.Name }}/ingress-controller/values.internal-alb-default.yaml

  - name: internal-nlb-default
    namespace: ingress-controller
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    version: 4.2.0
    condition: internal-nlb-default.enabled
    missingFileHandler: Warn
    values:
      - ./values.internal-nlb-default.yaml
      - ../../{{ .Environment.Name }}/ingress-controller/values.internal-nlb-default.yaml
