serviceAccount:
  create: true
  name: aws-load-balancer-controller

# for template
internal:
  alb:
    default:
      enabled:
      hosts:
  nlb:
    default:
      enabled:

external:
  alb:
    default:
      enabled:
      hosts:
  nlb:
    default:
      enabled:

# For conditional release per env
external-alb-default:
  enabled:

external-nlb-default:
  enabled:

internal-alb-default:
  enabled:

internal-nlb-default:
  enabled: