helmBinary: /tmp/helm

environments:
  dev:
    values: []

repositories:
  - name: sense-agent
    url: s3://sdx-eks-artifacts/{{ .Environment.Name }}/charts/sense-agent

missingFileHandler: Error

releases:
  - name: sense-agent
    namespace: sense
    createNamespace: true
    chart: sense-agent/sense-agent
    version: 0.0.1
    missingFileHandler: Warn
    values:
      - ./values.yaml
      - ../../{{ .Environment.Name }}/sense-agent/values.yaml