repos:
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.17 # Get from: https://github.com/gruntwork-io/pre-commit/releases
  hooks:
    - id: tflint
      args:
        - "--module"
        - "--config=.tflint.hcl"
    - id: terraform-validate
    - id: terraform-fmt
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.75.0 # Get from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_tfsec
#    - id: terraform_docs
#      args:
#        - --hook-config=--path-to-file=README.md
#        - --hook-config=--add-to-existing-file=true
#        - --hook-config=--create-file-if-not-exist=true