apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: backend-sense-auth
spec:
  selector:
    matchLabels:
      app: sdx-sense-auth
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: sdx-sense-auth
    spec:
      containers:
      - name: sdx-sense-auth
        image: 342446142760.dkr.ecr.ap-southeast-1.amazonaws.com/sense_auth:latest
        ports:
        - containerPort: 8080