kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: sdx-sense-auth
  name: sdx-sense-goauthbase-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: sdx-sense-auth