{{- range $k, $rangeItem := .Values.deployments }}
  {{- with $ }}
  {{- if or .Values.enabled $rangeItem.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default $k $rangeItem.name }}
  namespace: {{ .Values.namespace | default "sense" }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/app-name: {{ default $k $rangeItem.name }}
spec:
  replicas: {{ default $rangeItem.replicas .Values.replicas }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/app-name: {{ default $k $rangeItem.name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/app-name: {{ default $k $rangeItem.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ default $k $rangeItem.name }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/{{ default $rangeItem.imageName $rangeItem.name $k | replace "-"  "_" }}:{{ default .Values.image.tag $rangeItem.imageTag | default "latest" }}"
          volumeMounts:
            {{- with concat .Values.commons.mounts $rangeItem.mounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
          ports:
            {{- with concat .Values.commons.ports $rangeItem.ports }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.healthcheck.enabled }}
            - containerPort: {{ .Values.healthcheck.port }}
              name: healthcheck
            {{- end }}
          env:
            {{- with concat .Values.commons.envs $rangeItem.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: SENSE_ENV
              value: {{ .Values.env }}
            - name: SENSE_MODULE
              value: {{ default $k $rangeItem.name }}
          {{- if .Values.healthcheck.enabled }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
           {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- end }}
          resources:
          {{- with merge .Values.resources $rangeItem.resources }}
          {{- toYaml . | nindent 12 }}
      {{- end }}
      volumes:
      {{- with concat .Values.commons.volumes $rangeItem.volumes }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      nodeSelector:
      {{- with merge .Values.nodeSelector $rangeItem.nodeSelector }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
      {{- with merge .Values.affinity $rangeItem.affinity }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      {{- with concat .Values.tolerations $rangeItem.tolerations }}
      {{- toYaml . | nindent 8 }}
  {{- end }}
---
{{- end }}
  {{- end }}
  {{- end }}