#helmBinary: /tmp/helm

environments:
  dev:
    values:
      - ./values.yaml
      - ../../dev/monitoring/values.yaml
      - clusterName: {{ requiredEnv "CLUSTER_NAME" }}
      - accountId: {{ requiredEnv "AWS_ACC" }}
      - namespace: "monitoring"

repositories:
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: jaegertracing
    url:  https://jaegertracing.github.io/helm-charts

missingFileHandler: Error

releases:
  - name: monitoring
    namespace: monitoring
    createNamespace: true
    chart: "."
    version: 0.0.1
    missingFileHandler: Warn
    values:
      - ./values.yaml
      - ../../{{ .Environment.Name }}/monitoring/values.yaml
#    hooks:
#      - events: [ "presync" ]
#        showlogs: true
#        command: "./scripts/cluster-pre.sh"
#        args:
#          - "-c"
#          - "{{`{{ .Values.clusterName }}`}}"
#          - "-n"
#          - "{{`{{ .Values.namespace }}`}}"


  - name: kubernetes-dashboard
    namespace: monitoring
    createNamespace: true
    chart: kubernetes-dashboard/kubernetes-dashboard
    version: 5.7.0
    missingFileHandler: Warn
    values:
      - ./values.kubernetes-dashboard.yaml
      - ../../{{ .Environment.Name }}/cluster-common/values.kubernetes-dashboard.yaml

  - name: metrics-server
    namespace: monitoring
    createNamespace: true
    chart: metrics-server/metrics-server
    version: 3.8.2
    missingFileHandler: Warn
    values:
      - ./values.metrics-server.yaml
      - ../../{{ .Environment.Name }}/monitoring/values.metrics-server.yaml

  - name: jaegertracing
    namespace: monitoring
    createNamespace: true
    chart: jaegertracing/jaegertracing
    version: 3.8.2
    missingFileHandler: Warn
    condition: jaegertracing.enabled
    values:
      - ./values.jaegertracing.yaml
      - ../../{{ .Environment.Name }}/cluster-common/values.jaegertracing.yaml
