helmBinary: /tmp/helm

environments:
  dev:
    values:
      - ./values.yaml
      - ../../dev/monitoring/values.yaml
      - clusterName: {{ requiredEnv "CLUSTER_NAME" }}
      - accountId: {{ requiredEnv "AWS_ACC" }}
      - namespace: "monitoring"

repositories:
  - name: monitoring
    url: s3://sdx-eks-artifacts/{{ .Environment.Name }}/charts/monitoring
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: jaegertracing
    url:  https://jaegertracing.github.io/helm-charts
  - name: fluent
    url: https://fluent.github.io/helm-charts

missingFileHandler: Error

releases:
  - name: monitoring
    namespace: monitoring
    createNamespace: true
    chart: monitoring/monitoring
    version: 0.0.2
    missingFileHandler: Warn
    values:
      - ./values.yaml
      - ../../{{ .Environment.Name }}/monitoring/values.yaml

  - name: kubernetes-dashboard
    namespace: monitoring
    createNamespace: true
    chart: kubernetes-dashboard/kubernetes-dashboard
    version: 5.7.0
    missingFileHandler: Warn
    values:
      - ./values.kubernetes-dashboard.yaml
      - ../../{{ .Environment.Name }}/monitoring/values.kubernetes-dashboard.yaml

  - name: metrics-server
    namespace: monitoring
    createNamespace: true
    chart: metrics-server/metrics-server
    version: 3.8.2
    missingFileHandler: Warn
    values:
      - ./values.metrics-server.yaml
      - ../../{{ .Environment.Name }}/monitoring/values.metrics-server.yaml

  - name: jaegertracing
    namespace: monitoring
    createNamespace: true
    chart: jaegertracing/jaeger
    version: 0.58.0
    missingFileHandler: Warn
    condition: jaegertracing.enabled
    values:
      - ./values.jaegertracing.yaml
      - ../../{{ .Environment.Name }}/monitoring/values.jaegertracing.yaml

  - name: fleuntd
    namespace: monitoring
    createNamespace: true
    chart: fluent/fluentd
    version: 0.3.9
    missingFileHandler: Warn
    values:
      - ./values.fluentd.yaml
      - ../../{{ .Environment.Name }}/monitoring/values.fluentd.yaml