namespace: monitoring
component: monitoring
env:

jaegertracing:
  enabled: false

kube:
  hostname:
  ingressClassName:

opensearch:
  enabled: true
  hostname:
  ingressClassName:
  openToLocal: false
  vpcEndpoint: