component: monitoring

jaegertracing:
  enabled: false

kube:
  hostname:
  ingressClassName:

opensearch:
  enabled: true
  hostname:
  ingressClassName:
  openToLocal: false
  vpcEndpoint:
  endpoint: