apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: {{ .Values.awsAuth.boostrap.roleArn }}
      username: system:node:{{"{{"}}EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: {{ .Values.awsAuth.pipeline.roleArn }}
      username: pipeline-role
    - groups:
      - system:masters
      rolearn: {{ .Values.awsAuth.bastion.roleArn }}
      username: bastion-role    
    - groups:
      - eks-console-dashboard-view-full-access-group
      rolearn: {{ .Values.awsAuth.eksConsoleDashboard.roleArn }}
      username: admin-role

