{{- if .Values.secretstore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-aws-secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.secretstore.serviceAccount.name }}
            namespace: {{ .Values.namespace | default "cluster-common" }}
{{- end }}