env: dev
namespace: sense-backbone
chartVer: 0.0.3

nats:
  serverCert:
    name: nats-server-cert
    secretName: nats-server-cert
    commonName: nats.sense-dev.com
    sans:
      - nats.sense-backbone.svc.cluster.local