env: dev
namespace: sense
chartVer: 0.0.5

enabled: false

hostname:
  internal:
  external:

image:
  repository: 342446142760.dkr.ecr.ap-southeast-1.amazonaws.com

replicas: 1

autoscaling:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

secrets:
  commons: []
  services:
    - name: agent-config
      key: agent.config.yaml
      secretKey: dev/sdx/agent/common

certs: []

commons:
  envs: &commonEnvs
    - name: CLIENT_CA_PATH
      value: "/etc/sense/cert/backend/client/ca.crt"
    - name: CLIENT_CERT_PATH
      value: "/etc/sense/cert/backend/client/tls.crt"
    - name: CLIENT_KEY_PATH
      value: "/etc/sense/cert/backend/client/tls.key"
  volumes: &commonVolumes
    # --- configs and secrets
    - name: common-config
      configMap:
        name: common-config
    - name: init-map
      secret:
        secretName: init
    - name: mongodb
      secret:
        secretName: mongodb
    - name: redis
      secret:
        secretName: redis
    - name: backend
      secret:
        secretName: backend
    - name: rabbitmq
      secret:
        secretName: rabbitmq
    - name: broker
      secret:
        secretName: broker
    - name: elasticsearch
      secret:
        secretName: elasticsearch
    - name: nats
      secret:
        secretName: nats
    - name: documentdb-ca
      secret:
        secretName: documentdb-ca
    # --- certificates
    - name: backend-client-cert
      secret:
        secretName: backend-client-cert
    - name: mongo-client-cert
      secret:
        secretName: mongo-client-cert
    - name: nats-client-cert
      secret:
        secretName: nats-client-cert
  mounts: &commonMounts
    # --- configs and secrets
    - name: common-config
      readOnly: true
      mountPath: /etc/sense/conf/dev.config.yaml
      subPath: dev.config.yaml
    - name: init-map
      readOnly: true
      mountPath: /etc/sense/conf/init_config.yaml
      subPath: init_config.yaml
    - name: mongodb
      readOnly: true
      mountPath: /etc/sense/conf/mongodb_config.yaml
      subPath: mongodb_config.yaml
    - name: redis
      readOnly: true
      mountPath: /etc/sense/conf/redis_config.yaml
      subPath: redis_config.yaml
    - name: rabbitmq
      readOnly: true
      mountPath: /etc/sense/conf/rabbitmq_config.yaml
      subPath: rabbitmq_config.yaml
    - name: broker
      readOnly: true
      mountPath: /etc/sense/conf/broker_config.yaml
      subPath: broker_config.yaml
    - name: elasticsearch
      readOnly: true
      mountPath: /etc/sense/conf/elasticsearch_config.yaml
      subPath: elasticsearch_config.yaml
    - name: nats
      readOnly: true
      mountPath: /etc/sense/conf/nats_config.yaml
      subPath: nats_config.yaml
    # --- certificates
    - name: backend-client-cert
      readOnly: true
      mountPath: /etc/sense/cert/backend/client/
    - name: nats-client-cert
      readOnly: true
      mountPath: /etc/sense/cert/nats/
    - name: mongo-client-cert
      readOnly: true
      mountPath: /etc/sense/cert/mongo/
    - name: documentdb-ca
      readOnly: true
      mountPath: /etc/sense/cert/documentdb/ca.pem
      subPath: ca.pem

deployments:
  agent-sniff:
    enabled: true
    env:
      - name: SENSE_CONFIG_FILES
        value: "default.config agent.config"
      - name: SENSE_MODULE
        value: "sniff_agent"
      - name: SENSE_AGENT
        value: "sniff"
    volumes:
      - name: agent-config
        secret:
          secretName: agent-config
    mounts:
      - name: agent-config
        mountPath: conf/agent.config.yaml
        subPath: agent.config.yaml
  agent-dbtopics:
    enabled: true
    env:
      - name: SENSE_CONFIG_FILES
        value: "default.config agent.config"
      - name: SENSE_MODULE
        value: "sniff_agent"
      - name: SENSE_AGENT
        value: "dbtopics"
    volumes:
      - name: agent-config
        secret:
          secretName: agent-config
    mounts:
      - name: agent-config
        mountPath: conf/agent.config.yaml
        subPath: agent.config.yaml
  agent-elastic:
    enabled: true
    env:
      - name: SENSE_CONFIG_FILES
        value: "default.config agent.config"
      - name: SENSE_MODULE
        value: "sniff_agent"
      - name: SENSE_AGENT
        value: "elastic"
    volumes:
      - name: agent-config
        secret:
          secretName: agent-config
    mounts:
      - name: agent-config
        mountPath: conf/agent.config.yaml
        subPath: agent.config.yaml
  agent-kinesis:
    enabled: true
    env:
      - name: SENSE_CONFIG_FILES
        value: "default.config agent.config"
      - name: SENSE_MODULE
        value: "sniff_agent"
      - name: SENSE_AGENT
        value: "kinesis"
    volumes:
      - name: agent-config
        secret:
          secretName: agent-config
    mounts:
      - name: agent-config
        mountPath: conf/agent.config.yaml
        subPath: agent.config.yaml
  bridge-agent-dev-nats-dev-rmq:
    enabled: true
    imageName: sense_bridge_agent
    ports: []
    nodeSelector: {}
    tolerations: []
    affinity: {}
    autoscaling: {}
    resources: {}
    env:
      - name: SENSE_ENV
        value: dev
      - name: BRIDGE_ENV
        value: dev
      - name: SENSE_MODULE
        value: bridge_agent
      - name: BRIDGE_CONFIG_PREFIX
        value: nats-rmq
    volumes: []
    mounts: []
  bridge-agent-dev-rmq-qa-nats:
    enabled: true
    imageName: sense_bridge_agent
    ports: []
    nodeSelector: {}
    tolerations: []
    affinity: {}
    autoscaling: {}
    resources: {}
    env:
      - name: SENSE_ENV
        value: dev
      - name: BRIDGE_ENV
        value: dev
      - name: SENSE_MODULE
        value: bridge_agent
      - name: BRIDGE_CONFIG_PREFIX
        value: rmq-nats
    volumes: []
    mounts: []
