helmBinary: {{ requiredEnv "HELM_BINARY" }}

environments:
  dev:
    values:
      - ./values.yaml
      - ../../dev/global.yaml.gotmpl
      - ../../dev/sense-backbone/values.yaml

repositories:
  - name: sense-backbone
    url: s3://sdx-eks-artifacts/charts/sense-backbone
  - name: nats
    url: https://nats-io.github.io/k8s/helm/charts/

missingFileHandler: Error

releases:
  - name: sense-backbone
    namespace: sense-backbone
    createNamespace: true
    chart: sense-backbone/sense-backbone
    version: {{ .Values.chartVer | quote }}
    missingFileHandler: Warn
    values:
      - ./values.yaml
      - ./values.yaml.gotmpl
      - ../../{{ .Environment.Name }}/sense-backbone/values.yaml
      - ../../{{ .Environment.Name }}/sense-backbone/values.yaml.gotmpl
      - ./values.nats.yaml
      - ../../{{ .Environment.Name }}/sense-backbone/values.nats.yaml

  - name: nats
    namespace: sense-backbone
    createNamespace: true
    chart: nats/nats
    version: 0.17.4
    missingFileHandler: Warn
    condition: nats.enabled
    needs:
      - sense-backbone
    values:
      - ./values.nats.yaml
      - ../../{{ .Environment.Name }}/sense-backbone/values.nats.yaml
