helmBinary: {{ requiredEnv "HELM_BINARY" }}

environments:
  dev:
    values: []

repositories:
  - name: sense-frontend-portal
    url: s3://sdx-eks-artifacts/charts/sense-frontend-portal

missingFileHandler: Error

releases:
  - name: sense-frontend-portal
    namespace: sense
    createNamespace: true
    chart: sense-frontend-portal/sense-frontend-portal
    version: 0.0.4
    missingFileHandler: Warn
    values:
      - ./values.yaml
      - ../../{{ .Environment.Name }}/sense-frontend-portal/values.yaml
      - ../../{{ .Environment.Name }}/sense-frontend-portal/nginx.config.yaml
      - ../../{{ .Environment.Name }}/sense-frontend-portal/html.config.yaml