env: dev

vpcId: vpc-09a58d6d
accountId: 342446142760

external-alb-default:
  enabled: true

external-nlb-default:
  enabled: true

internal-alb-default:
  enabled: false

internal-nlb-default:
  enabled: true