include:
  - cicd/templates/.common.yml

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never
    - if: '$ENV' # ENV explicitly submitted
    - if: '$ENV && $CI_COMMIT_REF_PROTECTED == "true"' # ENV explicitly submitted and protected branch
    - if: '$CI_COMMIT_BRANCH =~ /^develop/ || $CI_COMMIT_BRANCH =~ /^release\//'


stages:
  - trigger-pipeline
  - release


release_tag:
  stage: release
  extends: .release_tag
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
    - if: '$ENV == "release/tag"'
  script:
    - |
      if [ -z "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" ]; then
        export TAG_NAME="v1.0.$CI_PIPELINE_IID-$CI_COMMIT_BRANCH-$(date +'%Y%m%d')"
      else
        export TAG_NAME="v1.0.$CI_PIPELINE_IID-$CI_MERGE_REQUEST_TARGET_BRANCH_NAME-$(date +'%Y%m%d')"
      fi
    - !reference [.release_tag, script]


eks-pipeline:ami-image-builder:
  stage: trigger-pipeline
  variables:
    AWS_REPO_TAG: $AWS_REPO_TAG
    AMI_OWNER: $AMI_OWNER
    AMI_NAME: $AMI_NAME
  rules:
    - if: '$ENV =~ /^dev/ || $ENV =~ /^qa/ || $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "release/dev" || $CI_COMMIT_BRANCH == "release/qa"'
      variables:
        ENV: dev/eks/ami
      when: manual
    - if: '$ENV =~ /^prod/ || $ENV =~ /^intra/ || $CI_COMMIT_BRANCH == "release/prod" || $CI_COMMIT_BRANCH == "release/intra"'
      variables:
        ENV: prod/eks/ami
      when: manual
  trigger:
    include:
      - cicd/gitlab-ci/Image-Builder.yml


eks-pipeline:app-eks-terraform:
  stage: trigger-pipeline
  variables:
    DEPLOYMENT_INSTANCE_ID: $DEPLOYMENT_INSTANCE_ID
  rules:
    - if: '$ENV =~ /^dev/ || $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "release/dev"'
      variables:
        ENV: dev/app/eks
      when: manual
  trigger:
    include:
      - cicd/gitlab-ci/App-EKS-terraform.yml


eks-pipeline:app-eks-chart-publish:
  stage: trigger-pipeline
  rules:
    - if: '$ENV =~ /^dev/ || $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "release/dev"'
      variables:
        ENV: dev
      when: manual
  trigger:
    include:
      - cicd/gitlab-ci/App-EKS-charts-publish.yml


eks-pipeline:app-eks-chart-deploy:
  stage: trigger-pipeline
  rules:
    - if: '$ENV =~ /^dev/ || $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "release/dev"'
      variables:
        ENV: dev
      when: manual
  trigger:
    include:
      - cicd/gitlab-ci/App-EKS-charts-deploy.yml


eks-pipeline:sol-eks-terraform:
  stage: trigger-pipeline
  rules:
    - if: '$ENV =~ /^dev/ || $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "release/dev"'
      variables:
        ENV: dev/sol/eks
      when: manual
    - if: '$ENV =~ /^qa/ || $CI_COMMIT_BRANCH == "release/qa"'
      variables:
        ENV: qa/sol/eks
      when: manual
    - if: '$ENV =~ /^prod/ || $CI_COMMIT_BRANCH == "release/prod"'
      variables:
        ENV: prod/sol/eks
      when: manual
    - if: '$ENV =~ /^intra/ || $CI_COMMIT_BRANCH == "release/intra"'
      variables:
        ENV: intra/sol/eks
      when: manual
  trigger:
    include:
      - cicd/gitlab-ci/Solace-EKS-terraform.yml


eks-pipeline:solace-eks-chart-deploy:
  stage: trigger-pipeline
  variables:
  rules:
    - if: '$ENV =~ /^dev/ || $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "release/dev"'
      variables:
        ENV: dev/sol/eks
      when: manual
    - if: '$ENV =~ /^qa/ || $CI_COMMIT_BRANCH == "release/qa"'
      variables:
        ENV: qa/sol/eks
      when: manual
    - if: '$ENV =~ /^prod/ || $CI_COMMIT_BRANCH == "release/prod"'
      variables:
        ENV: prod/sol/eks
      when: manual
    - if: '$ENV =~ /^intra/ || $CI_COMMIT_BRANCH == "release/intra"'
      variables:
        ENV: intra/sol/eks
      when: manual
  trigger:
    include:
      - cicd/gitlab-ci/Solace-EKS-charts-deploy.yml

