include:
  - cicd/templates/.common.yml

stages:
  - publish
  - deploy

variables:
  HELM_ROOT: $HELM_ROOT


.helm-builder:
  extends: .awscli-root-builder


.publish-chart:
  stage: publish
  extends: .helm-builder
  environment: $ENV
  script:
    - if [ -z "$CHART_NAME" ]; then echo "variable CHART_NAME must be set." && exit 1; fi
    - if [ -z "$HELM_ROOT" ]; then echo "variable HELM_ROOT must be set." && exit 1; fi
    - chmod +x cicd/scripts/helm-publish-chart.sh
    - cicd/scripts/helm-publish-chart.sh "$CHART_NAME" "$HELM_ROOT"


.deploy-helmfile:
  stage: deploy
  extends: .helm-builder
  environment: $ENV
  script:
    - if [ -z "$SCP_SOURCE_FOLDER" ]; then echo "variable SCP_SOURCE_FOLDER must be set." && exit 1; fi
    - if [ -z "$CHART_NAME" ]; then echo "variable CHART_NAME must be set." && exit 1; fi
    - if [ -z "$HELM_ENV" ]; then echo "variable HELM_ENV must be set." && exit 1; fi
    - if [ -z "$ROLE_ARN" ]; then echo "variable ROLE_ARN must be set." && exit 1; fi
    - if [ -z "$EKS_CLUSTER_NAME" ]; then echo "variable EKS_CLUSTER_NAME must be set." && exit 1; fi
    - if [ -z "$DEPLOYMENT_INSTANCE_ID" ]; then echo "variable DEPLOYMENT_INSTANCE_ID must be set." && exit 1; fi
    - |
      echo "SCP helmfiles ... "
      export DEST=/home/ssm-user/tmp/charts-$CI_COMMIT_REF_SLUG/$CHART_NAME
      export INSTANCE_ID=$DEPLOYMENT_INSTANCE_ID
      export SOURCE=$SCP_SOURCE_FOLDER/repo.zip
    - !reference [.ssm-clean-scp, script]
    - |
      echo "unziping $DEST/repo.zip ..."
      export SSH_CMD="unzip -o $DEST/repo.zip -d $DEST/; find $DEST -type f -name "*.sh" -exec chmod +x {} \;"
    - !reference [.ssm-ssh-sh, script]
    - |
      echo "Executing helm upgrade CLUSTER_NAME:$EKS_CLUSTER_NAME CHART_NAME:$CHART_NAME TAG:$TAG HELM_ENV:$HELM_ENV"
      if [ -z "$TAG" ]; then
            export SSH_CMD="sudo bash -c 'export HELM_BINARY=helm; export CLUSTER_NAME=$EKS_CLUSTER_NAME; helmfile -e $HELM_ENV -f $DEST/$HELMFILE_ROOT/helmfile.yaml apply'"
      else
            export SSH_CMD="sudo bash -c 'export HELM_BINARY=helm; export CLUSTER_NAME=$EKS_CLUSTER_NAME; helmfile -e $HELM_ENV -f $DEST/$HELMFILE_ROOT/helmfile.yaml apply --set image.tag=$TAG'"
      fi
    - !reference [.ssm-ssh-sh, script]
