env: dev
namespace: sense
chartVer: 0.0.4

hostname: qa2.sense-dev.com
#hostname: qa.sense-dev.com

image:
  repository: 342446142760.dkr.ecr.ap-southeast-1.amazonaws.com

autoscaling:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingressClassName: external-alb-default

commons:
  envs:
    - name: MODULE
      value: "adex"
  volumes:
    - name: frontend-nginx-config
      configMap:
        name: frontend-nginx-config
    - name: portal-nginx-config
      configMap:
        name: portal-nginx-config
  mounts:
    - name: frontend-nginx-config
      readOnly: true
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
    - name: portal-nginx-config
      readOnly: true
      mountPath: /etc/nginx/default.d/nginx-adex.conf
      subPath: nginx-adex.conf

deployments:
  frontend-portal:
    env: []
    volumes: []
    mounts: []
