env: dev

jaegertracing:
  enabled: false

kube:
  hostname: k8.sense-dev.com
  ingressClassName: external-alb-default

opensearch:
  enabled: true
  hostname: opensearch.sense-dev.com
  ingressClassName: external-alb-default
  openToLocal: false
  vpcEndpoint: vpc-dev-sdx-es-kgfhpvtfio32mmlzxw22wbgi4i.ap-southeast-1.es.amazonaws.com


image:
  repository: 342446142760.dkr.ecr.ap-southeast-1.amazonaws.com/
  tag: latest
  pullPolicy: Always
  fluentd:
    name: sense_fluentd

resources:
  fluentd:
    limits:
      memory: 200Mi
      cpu: 0.1

