apiVersion: v2
name: cluster

version: 0.1.22 # following eks version

appVersion: 0.1.22 # following eks version

# versions are chart version, not app version.
dependencies:
  - name: external-secrets
    version: 0.5.2
    repository: https://charts.external-secrets.io
  - name: kubernetes-dashboard
    version: 5.0.5
    repository: https://kubernetes.github.io/dashboard/
  - name: aws-load-balancer-controller
    version: 1.4.1 # image version v2.3.1
    repository: https://aws.github.io/eks-charts
  - name: metrics-server
    version: 3.7.0
    repository: https://kubernetes-sigs.github.io/metrics-server/