helmBinary: /tmp/helm

environments:
  dev:
    values:
      - ./values.yaml
      - ../../dev/cluster-common/values.yaml
      - clusterName: {{ requiredEnv "CLUSTER_NAME" }}
      - accountId: {{ requiredEnv "AWS_ACC" }}
      - namespace: "cluster-common"

repositories:
  - name: aws-load-balancer-controller
    url:  https://aws.github.io/eks-charts
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: external-secrets
    url: https://charts.external-secrets.io
  - name: cluster-autoscaler
    url: https://kubernetes.github.io/autoscaler
  - name: cert-manager
    url: https://charts.jetstack.io
  - name: cert-manager-awspca
    url: https://cert-manager.github.io/aws-privateca-issuer

missingFileHandler: Error

releases:
  - name: cluster-common
    namespace: cluster-common
    createNamespace: true
    chart: "."
    version: 0.0.1
    missingFileHandler: Warn
    values:
      - ./values.yaml
      - ../../{{ .Environment.Name }}/cluster-common/values.yaml
    hooks:
      - events: [ "presync" ]
        showlogs: true
        command: "./scripts/cluster-pre.sh"
        args:
          - "-c"
          - "{{`{{ .Values.clusterName }}`}}"
          - "-n"
          - "{{`{{ .Values.namespace }}`}}"


  - name: aws-load-balancer-controller
    namespace: cluster-common
    createNamespace: true
    chart: aws-load-balancer-controller/aws-load-balancer-controller
    version: 1.4.2
    missingFileHandler: Warn
    disableValidationOnInstall: true # CRD
    needs:
      - cert-manager
      - cluster-common
    values:
      - ./values.aws-load-balancer-controller.yaml
      - ../../{{ .Environment.Name }}/cluster-common/values.aws-load-balancer-controller.yaml.gotmpl
    hooks:
      - events: [ "presync" ]
        showlogs: true
        command: "./scripts/awslbcontroller-pre.sh"
        args:
          - "-a"
          - "{{`{{ .Values.accountId }}`}}"
          - "-e"
          - "{{`{{ .Environment.Name }}`}}"
          - "-c"
          - "{{`{{ .Values.clusterName }}`}}"
          - "-n"
          - "{{`{{ .Values.namespace }}`}}"

  - name: kubernetes-dashboard
    namespace: cluster-common
    createNamespace: true
    chart: kubernetes-dashboard/kubernetes-dashboard
    version: 5.7.0
    missingFileHandler: Warn
    values:
      - ./values.kubernetes-dashboard.yaml
      - ../../{{ .Environment.Name }}/cluster-common/values.kubernetes-dashboard.yaml.gotmpl

  - name: metrics-server
    namespace: cluster-common
    createNamespace: true
    chart: metrics-server/metrics-server
    version: 3.8.2
    missingFileHandler: Warn
    values:
      - ./values.metrics-server.yaml
      - ../../{{ .Environment.Name }}/cluster-common/values.metrics-server.yaml.gotmpl

  - name: external-secrets
    namespace: cluster-common
    createNamespace: true
    chart: external-secrets/external-secrets
    version: 0.5.8
    missingFileHandler: Warn
    values:
      - ./values.external-secrets.yaml
      - ../../{{ .Environment.Name }}/cluster-common/values.external-secrets.yaml.gotmpl

  - name: cluster-autoscaler
    namespace: cluster-common
    createNamespace: true
    chart: cluster-autoscaler/cluster-autoscaler
    version: 9.19.2
    missingFileHandler: Warn
    disableValidationOnInstall: true # CRD
    needs:
      - cluster-common
    values:
      - ./values.cluster-autoscaler.yaml
      - ../../{{ .Environment.Name }}/cluster-common/values.cluster-autoscaler.yaml.gotmpl
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "./scripts/clusterautoscaler-pre.sh"
        args:
          - "-a"
          - "{{`{{ .Values.accountId }}`}}"
          - "-e"
          - "{{`{{ .Environment.Name }}`}}"
          - "-c"
          - "{{`{{ .Values.clusterName }}`}}"
          - "-n"
          - "{{`{{ .Values.namespace }}`}}"
      - events: ["postsync"]
        showlogs: true
        command: "./scripts/clusterautoscaler-post.sh"
        args:
          - "-a"
          - "{{`{{ .Values.accountId }}`}}"
          - "-e"
          - "{{`{{ .Environment.Name }}`}}"
          - "-c"
          - "{{`{{ .Values.clusterName }}`}}"
          - "-n"
          - "{{`{{ .Values.namespace }}`}}"

  - name: cert-manager
    namespace: cluster-common
    createNamespace: true
    chart: cert-manager/cert-manager
    version: 1.9.1
    missingFileHandler: Warn
    disableValidationOnInstall: true # CRD
    values:
      - ./values.cert-manager.yaml
      - ../../{{ .Environment.Name }}/cluster-common/values.cert-manager.yaml.gotmpl

  - name: cert-manager-awspca
    namespace: cluster-common
    createNamespace: true
    chart: cert-manager-awspca/aws-privateca-issuer
    version: 1.2.0
    missingFileHandler: Warn
    disableValidationOnInstall: true # CRD
    needs:
      - cert-manager