helmBinary: {{ requiredEnv "HELM_BINARY" }}

environments:
  dev:
    values:
      - ./values.yaml
      - ../../dev/cluster-common/values.yaml
      - clusterName: {{ requiredEnv "CLUSTER_NAME" }}
      - accountId: {{ requiredEnv "AWS_ACC" }}
      - namespace: "cluster-common"

repositories:
  - name: cluster-common
    url: s3://sdx-eks-artifacts/{{ .Environment.Name }}/charts/cluster-common
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/
  - name: external-secrets
    url: https://charts.external-secrets.io
  - name: cluster-autoscaler
    url: https://kubernetes.github.io/autoscaler
  - name: cert-manager
    url: https://charts.jetstack.io
  - name: cert-manager-awspca
    url: https://cert-manager.github.io/aws-privateca-issuer

missingFileHandler: Error

releases:
  - name: cluster-common
    namespace: cluster-common
    createNamespace: true
    chart: cluster-common/cluster-common
    version: 0.0.2
    missingFileHandler: Warn
    disableValidationOnInstall: true # CRD
    values:
      - ./values.yaml
      - ../../{{ .Environment.Name }}/cluster-common/values.yaml
    needs:
      - external-secrets
      - cert-manager-awspca
    hooks:
      - events: [ "presync" ]
        showlogs: true
        command: "./scripts/cluster-pre.sh"
        args:
          - "-c"
          - "{{`{{ .Values.clusterName }}`}}"
          - "-n"
          - "{{`{{ .Values.namespace }}`}}"
      - events: [ "presync" ]
        showlogs: true
        command: "./scripts/ebscsi-pre.sh"
        args:
          - "-c"
          - "{{`{{ .Values.clusterName }}`}}"
          - "-n"
          - "{{`{{ .Values.namespace }}`}}"

  - name: external-dns
    namespace: cluster-common
    createNamespace: true
    chart: external-dns/external-dns
    version: 1.10.1
    missingFileHandler: Warn
    condition: external-dns.enabled
    needs:
      - cluster-common
    values:
      - ./values.external-dns.yaml
      - ../../{{ .Environment.Name }}/cluster-common/values.external-dns.yaml
    hooks:
      - events: [ "presync" ]
        showlogs: true
        command: "./scripts/externaldns-pre.sh"
        args:
          - "-a"
          - "{{`{{ .Values.accountId }}`}}"
          - "-e"
          - "{{`{{ .Environment.Name }}`}}"
          - "-c"
          - "{{`{{ .Values.clusterName }}`}}"
          - "-n"
          - "{{`{{ .Values.namespace }}`}}"

  - name: external-secrets
    namespace: cluster-common
    createNamespace: true
    chart: external-secrets/external-secrets
    version: 0.5.8
    missingFileHandler: Warn
    condition: external-secrets.enabled
    disableValidationOnInstall: true # CRD
    values:
      - ./values.external-secrets.yaml
      - ../../{{ .Environment.Name }}/cluster-common/values.external-secrets.yaml.gotmpl
    hooks:
      - events: [ "presync" ]
        showlogs: true
        command: "./scripts/secretaccess-pre.sh"
        args:
          - "-a"
          - "{{`{{ .Values.accountId }}`}}"
          - "-e"
          - "{{`{{ .Environment.Name }}`}}"
          - "-c"
          - "{{`{{ .Values.clusterName }}`}}"
          - "-n"
          - "{{`{{ .Values.namespace }}`}}"
      - events: [ "postsync" ]
        showlogs: true
        command: "sleep"
        args:
          - "45"

  - name: cluster-autoscaler
    namespace: cluster-common
    createNamespace: true
    chart: cluster-autoscaler/cluster-autoscaler
    version: 9.19.2
    missingFileHandler: Warn
    condition: cluster-autoscaler.enabled
    disableValidationOnInstall: true # CRD
    needs:
      - cluster-common
    values:
      - ./values.cluster-autoscaler.yaml
      - ../../{{ .Environment.Name }}/cluster-common/values.cluster-autoscaler.yaml.gotmpl
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "./scripts/clusterautoscaler-pre.sh"
        args:
          - "-a"
          - "{{`{{ .Values.accountId }}`}}"
          - "-e"
          - "{{`{{ .Environment.Name }}`}}"
          - "-c"
          - "{{`{{ .Values.clusterName }}`}}"
          - "-n"
          - "{{`{{ .Values.namespace }}`}}"
      - events: ["postsync"]
        showlogs: true
        command: "./scripts/clusterautoscaler-post.sh"
        args:
          - "-a"
          - "{{`{{ .Values.accountId }}`}}"
          - "-e"
          - "{{`{{ .Environment.Name }}`}}"
          - "-c"
          - "{{`{{ .Values.clusterName }}`}}"
          - "-n"
          - "{{`{{ .Values.namespace }}`}}"

  - name: cert-manager
    namespace: cluster-common
    createNamespace: true
    chart: cert-manager/cert-manager
    version: 1.9.1
    missingFileHandler: Warn
    condition: cert-manager.enabled
    disableValidationOnInstall: true # CRD
    values:
      - ./values.cert-manager.yaml

  - name: cert-manager-awspca
    namespace: cluster-common
    createNamespace: true
    chart: cert-manager-awspca/aws-privateca-issuer
    version: 1.2.0
    missingFileHandler: Warn
    condition: cert-manager.enabled
    disableValidationOnInstall: true # CRD
    needs:
      - cert-manager
    values:
      - ./values.cert-manager-acm.yaml
    hooks:
      - events: [ "presync" ]
        showlogs: true
        command: "./scripts/acmpca-pre.sh"
        args:
          - "-a"
          - "{{`{{ .Values.accountId }}`}}"
          - "-e"
          - "{{`{{ .Environment.Name }}`}}"
          - "-c"
          - "{{`{{ .Values.clusterName }}`}}"
          - "-n"
          - "{{`{{ .Values.namespace }}`}}"