component: common

secretstore:
  enabled: true
  serviceAccount:
    name: secrets-access-sa

# For conditional release per env
cert-manager:
  enabled: true

cluster-autoscaler:
  enabled: true

external-secrets:
  enabled: true
