helmBinary: /tmp/helm

environments:
  dev:
    values: []

repositories:
  - name: sense-frontend-auth
    url: s3://sdx-eks-artifacts/{{ .Environment.Name }}/charts/sense-frontend-auth

missingFileHandler: Error

releases:
  - name: sense-frontend-auth
    namespace: sense
    createNamespace: true
    chart: sense-frontend-auth/sense-frontend-auth
    version: 0.0.1
    missingFileHandler: Warn
    values:
      - ./values.yaml
      - ../../{{ .Environment.Name }}/sense-frontend-auth/values.yaml