# https://github.com/nats-io/k8s/blob/main/helm/charts/nats/values.yaml

nats:
  image: nats:2.8.4-alpine
  pullPolicy: IfNotPresent
  tls:
    secret:
      name: nats-server-cert
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"
    cipherSuites:
      - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
      - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
  jetstream:
    enabled: true
    uniqueTag: easy-dev-unique-tag
    memStorage:
      enabled: true
      size: 100Mi
    fileStorage:
      enabled: true
      storageDirectory: /data/nats
      claimStorageSize: "3Gi"
      bufferClaimSize: 5Gi
      existingClaim: nats-js-disk

cluster:
  enabled: false

auth:
  enabled: false