---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  namespace: kube-system
  name: cluster-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
---
