namespace: ingress-controller
chartVer: 0.0.5

# chart installing conditions for multi-envs
external-alb-default:
  enabled: true # enabled, portal/API access without FW

external-nlb-default:
  enabled: false # disabled, external NLB until we have any TCP servers to test

internal-alb-default:
  enabled: false

internal-nlb-default:
  enabled: true # DEV cross zone API, NATS access
