{{- if .Values.external.alb.default.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- with .Values.external.alb.default.annotations }}
  annotations:
    external.dns/group: "external"
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: external-alb-default-connect-nginx-ingress
  namespace: {{- .Values.namespace | quote }}
spec:
  # NOTE: 'alb' class will create/manage alb by AWS Load Balancer Controller
  #        and routes all traffic to ingress-nginx external-alb-default class
  ingressClassName: alb
  rules:
  {{- range .Values.external.alb.default.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - backend:
              service:
                name: external-alb-default-ingress-nginx-controller
                port:
                  number: 80
            path: /*
            pathType: ImplementationSpecific
          - backend:
              service:
                name: external-alb-default-ingress-nginx-controller
                port:
                  number: 443
            path: /*
            pathType: ImplementationSpecific
    {{- end }}
{{- end }}
