#apiVersion: kubernetes-client.io/v1
#kind: ExternalSecret
#metadata:
#  annotations: {}
#  name: mongo-config
#  namespace: sense
#spec:
#  backendType: secretsManager
#  data:
#    - key: dev/sdx/mongodb/credentials
#      name: mongo.config.yaml
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  namespace: sense
  name: sense-secret-store
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  provider:
    aws:
      service: SecretsManager
     #  role: arn:aws:iam::342446142760:role/terraform-eks-sdx-node # should have secret access
      region: ap-southeast-1
---
# example..
#apiVersion: external-secrets.io/v1beta1
#kind: ExternalSecret
#metadata:
#  name: mongo-test-config
#  namespace: sense
#  labels:
#    app.kubernetes.io/managed-by: Helm
#spec:
#  refreshInterval: 1m
#  secretStoreRef:
#    name: sense-secret-store
#    kind: SecretStore
#  target:
#    name:  mongo-test-config
#    creationPolicy: Owner
#  dataFrom:
#    - extract:
#        key: dev/sdx/mongodb/credentials
