apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  annotations: {}
  name: mongo-config
  namespace: sense
spec:
  backendType: secretsManager
  data:
    - key: dev/sdx/mongodb/credentials
      name: mongo.config.yaml
---
#apiVersion: kubernetes-client.io/v1
#kind: ExternalSecret
#metadata:
#  annotations: {}
#  name: kube.config
#  namespace: sense
#spec:
#  backendType: secretsManager
#  data:
#    - key: key here
#      name: kube.config.yaml