kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.env }}-config
  namespace: {{ include "sense.fullname" . }}
data:
  kube.config.yaml: >-
    bG9nZ2luZzoKICBjb2xvcjogdHJ1ZQoKbW9uZ286CiAgaG9zdDogIm1kYi1ybXEuc2Vuc2UtZGV2LmNvbSIKICB1c2VyOiAiYWRtaW4iCiAgcGFzc3dvcmQ6ICI0SWhQWG9KRGZ2WmpqS040VDVGeFNkUU9VUjNjaDNZNiIKICBhcHBwYXNzd29yZDogIlpOTlJJOVZ5Y3Y4VEpWWnpGVHlhNHlucVhGbFFxajE5IgoKcmVkaXM6CiAgICBob3N0OiAiZGV2LXJlZGlzLmdieHYyay4wMDAxLmFwc2UxLmNhY2hlLmFtYXpvbmF3cy5jb20iCiAgICBwb3J0OiA2Mzc5CiAgICBwYXNzd29yZDogIiIKICAgIGRiOiAxCgpuYXRzOgogIGVuZHBvaW50OiAibmF0c19jbGllbnQ6QUNlYThnaGFoYkBuYXRzLWNsaWVudC5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjQyMjIiCgpvcGVuOgogIHRyYWNpbmc6CiAgICBkaXNhYmxlZDogdHJ1ZQogICAgCmVsYXN0aWNzZWFyY2g6CiAgdXJsOiAiaHR0cHM6Ly92cGMtZGV2LXNkeC1lcy1rZ2ZocHZ0ZmlvMzJtbWx6eHcyMndiZ2k0aS5hcC1zb3V0aGVhc3QtMS5lcy5hbWF6b25hd3MuY29tIgogIGhvc3Q6ICJodHRwczovL3ZwYy1kZXYtc2R4LWVzLWtnZmhwdnRmaW8zMm1tbHp4dzIyd2JnaTRpLmFwLXNvdXRoZWFzdC0xLmVzLmFtYXpvbmF3cy5jb20iCiAgdXNlcm5hbWU6ICIiCiAgcGFzc3dvcmQ6ICIiCgpyYWJiaXRtcToKICBob3N0OiAibWRiLXJtcS5zZW5zZS1kZXYuY29tIgogIHVzZXJuYW1lOiAicmFiYml0YWRtaW4iCiAgcGFzc3dvcmQ6ICJhZG1pbiIKICBzeXN0ZW1fdXNlcjogInJhYmJpdF9zeXN0ZW0iCiAgc3lzdGVtX3Bhc3N3b3JkOiAieEt5d1ozZHNDdkdhTEdLNWg2bmN0SEQwNm5qN3J4aEkiCgpldGNkOgogIGVuYWJsZWQ6IGZhbHNl
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: auth-config
  namespace: {{ include "sense.fullname" . }}
data:
  auth.config.yaml: >-
    Y29nbml0bzoKICBlbmFibGVkOiB0cnVlCiAgY2xpZW50SWQ6ICIxdDNxaW03dmU0N2xvMDRuNmloajFobDZ2bCIKICB1c2VyUG9vbFJlZ2lvbjogImFwLXNvdXRoZWFzdC0xIgogIHVzZXJQb29sSWQ6ICJhcC1zb3V0aGVhc3QtMV83YzdMTkFuSUciICNvcHRpb25hbCBNRkEgdXNlciBwb29sCiAgandrc1VSTDogImh0dHBzOi8vY29nbml0by1pZHAuYXAtc291dGhlYXN0LTEuYW1hem9uYXdzLmNvbS9hcC1zb3V0aGVhc3QtMV83YzdMTkFuSUcvLndlbGwta25vd24vandrcy5qc29uIgogIGp3dER1cmF0aW9uTWluczogNjAgIyBleHRlbmRlZCBmb3IgZWFzaWVyIGRldmVsb3BtZW50CiAgIyB0ZWNocGFzcyBpbnRlZ3JhdGlvbiAtLSBzdGFydAogIHVzZXJwb29sOgogICAgcmVnaW9uOiAiYXAtc291dGhlYXN0LTEiCiAgICBpZDogImFwLXNvdXRoZWFzdC0xX29WSHRuMGZtcCIKICBjbGllbnQ6CiAgICBpZDogIjN0bW92NGlhaDF0Ym1saXNlajljNzM5Y2dhIgogICAgc2VjcmV0OiAiMXVsa2w0c20xcjE5dW1uOGNlNGI2cGhxZDJucHZmYTdpM2RnbGQ0MGU2aWcxZjNubmltNSIKICAjIHRlY2hwYXNzIGludGVncmF0aW9uIC0tIGVuZAoKb2F1dGgyOgogIGVuZHBvaW50OiAibG9naW4uc3RnLnRlY2hwYXNzLmdvdi5zZyIKCndoaXRlbGlzdDoKICBlbWFpbFBhdHRlcm5zOgogICAgLSBecm52ZW5rYXRlc2h3YXJpKCtbYS16QS1aMC05XSspezAsMX1AZ21haWwuY29tJAogICAgLSBebHZsMTAwcCgrW2EtekEtWjAtOV0rKXswLDF9QGdtYWlsLmNvbSQKICAgIC0gXmFhbmJ1KCtbYS16QS1aMC05XSspezAsMX1AcGFsby1pdC5jb20kICMgQWtpbGFuCiAgICAtIF5hbWluKCtbYS16QS1aMC05XSspezAsMX1AcGFsby1pdC5jb20kICMgQWxleAogICAgLSBeYW51anBhbDEyKCtbYS16QS1aMC05XSspezAsMX1AZ21haWwuY29tJCAjIEFudWoKICAgIC0gXmFudWpfcGFsKCtbYS16QS1aMC05XSspezAsMX1AbnNlYXJjaGdsb2JhbC5jb20kICMgQW51agogICAgLSBeYXphZHBhbCgrW2EtekEtWjAtOV0rKXswLDF9QG5zZWFyY2hnbG9iYWwuY29tJCAjIEF6YWQKICAgIC0gXmN0anNjdGpzKCtbYS16QS1aMC05XSspezAsMX1AZ21haWwuY29tJCAjIENsZW1lbnQKICAgIC0gXmJvc2NvX2Zlcm5hbmRvKCtbYS16QS1aMC05XSspezAsMX1AbnNlYXJjaGdsb2JhbC5jb20kICMgQm9zY28KICAgIC0gXmNoZXJpZV9hcmpvbigrW2EtekEtWjAtOV0rKXswLDF9QG5zZWFyY2hnbG9iYWwuY29tJCAjIENoZXJpZQogICAgLSBeLitAaGl2ZS5nb3Yuc2ckCiAgICAtIF4uK0BzaW11bGF0b3IuYW1hem9uc2VzLmNvbSQ=
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: clients-config
  namespace: {{ include "sense.fullname" . }}
data:
  clients.config.yaml: >-
    YXBpczoKICByYWJiaXRtcToKICAgIGhvc3Q6ICJtZGItcm1xLnNlbnNlLWRldi5jb20iCgplbGFzdGljc2VhcmNoOgogIGluZGljZXM6CiAgICBjbGllbnQ6ICJzbnNwLWNsaWVudC1sb2NhbCI=
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: topics-config
  namespace: {{ include "sense.fullname" . }}
data:
  topics.config.yaml: >-
        ZWxhc3RpY3NlYXJjaDoKICBpbmRpY2VzOgogICAgZXZlbnRzOiAic25zcC0tdG9waWNzLWV2ZW50cy1sb2NhbF8qIgogICAgdG9waWNzOiAic25zcC10b3BpY3MtbG9jYWwiCiAgICB0YWdjbG91ZDogInNuc3AtdG9waWNzLXRhZ2Nsb3VkLWxvY2FsIgogICAgdHJlbmQ6ICAic25zcC10b3BpY3MtdHJlbmQtbG9jYWwiCiAgICBwYXlsb2FkOiAic25zcC1zbmlmZi1sYXRlc3QtcGF5bG9hZC1sb2NhbCI=
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: onpremtopic-config
  namespace: {{ include "sense.fullname" . }}
data:
  onpremtopic.config.yaml: >-
    CgpzZHg6CiAgZHVtbXlwcm9qZWN0czogfC0KICAgIFt7InByb2plY3RJZCI6ICJjODcyOWVhYS03MDQ1LTRkZWItYTMzZi0xMDc1MDNjMWIwOTAiLCJwcm9qZWN0Q29kZSI6ICJQVUItV0FURVJXSVNFIiwicHJvamVjdE5hbWUiOiAiUFVCLVdBVEVSV0lTRSIsInpvbmUiOiAiSW50cmFuZXQifSwKICAgIAl7InByb2plY3RJZCI6ICJDMDc2ODY4Qi00QUMzLTRFNDAtOENGMy03NjZDQkE3N0Y4NDIiLCJwcm9qZWN0Q29kZSI6ICJORUEtU0VOU09SIiwicHJvamVjdE5hbWUiOiAiTkVBLVNFTlNPUiIsInpvbmUiOiAiSW50cmFuZXQiCiAgICAJfSx7InByb2plY3RJZCI6ICJDMDc2ODY4Qi00QUMzLTRFNDAtOENGMy03NjZDRkE3N0Y4NDYiLCJwcm9qZWN0Q29kZSI6ICJQVUJMSVNILVBVQi0wMSIsInByb2plY3ROYW1lIjogIkhEQi1IT1VTSU5HIiwiem9uZSI6ICJJbnRyYW5ldCIKICAgIAl9XQ==
type: Opaque
