kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.env }}-config
  namespace: {{ include "sense.fullname" . }}
data:
  kube.config.yaml: >-
    bG9nZ2luZzoKICBjb2xvcjogdHJ1ZQoKbW9uZ286CiAgaG9zdDogIm1kYi1ybXEuc2Vuc2UtZGV2LmNvbSIKICB1c2VyOiAiYXBwdXNlciIKICBhcHB1c2VyOiAiYXBwdXNlciIKICBwYXNzd29yZDogIjRJaFBYb0pEZnZaampLTjRUNUZ4U2RRT1VSM2NoM1k2IgogIGFwcHBhc3N3b3JkOiAiWk5OUkk5VnljdjhUSlZaekZUeWE0eW5xWEZsUXFqMTkiCgpyZWRpczoKICAgIGhvc3Q6ICJzZHgtZGV2LWNhY2hlLWdwLTAwMS5nYnh2MmsuMDAwMS5hcHNlMS5jYWNoZS5hbWF6b25hd3MuY29tIgogICAgcG9ydDogNjM3OQogICAgcGFzc3dvcmQ6ICIiCiAgICBkYjogMQoKbmF0czoKICBlbmRwb2ludDogIm5hdHNfY2xpZW50OkFDZWE4Z2hhaGJAbmF0cy1jbGllbnQuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDo0MjIyIgoKb3BlbjoKICB0cmFjaW5nOgogICAgZGlzYWJsZWQ6IHRydWUKICAgIAplbGFzdGljc2VhcmNoOgogIHVybDogImh0dHBzOi8vdnBjLWRldi1zZHgtZXMta2dmaHB2dGZpbzMybW1senh3MjJ3YmdpNGkuYXAtc291dGhlYXN0LTEuZXMuYW1hem9uYXdzLmNvbSIKICBob3N0OiAiaHR0cHM6Ly92cGMtZGV2LXNkeC1lcy1rZ2ZocHZ0ZmlvMzJtbWx6eHcyMndiZ2k0aS5hcC1zb3V0aGVhc3QtMS5lcy5hbWF6b25hd3MuY29tIgogIHVzZXJuYW1lOiAiIgogIHBhc3N3b3JkOiAiIgoKcmFiYml0bXE6CiAgaG9zdDogIm1kYi1ybXEuc2Vuc2UtZGV2LmNvbSIKICB1c2VybmFtZTogInJhYmJpdF9hZG1pbiIKICBwYXNzd29yZDogIjJSS2puak00eTZQaHdqMUx5QU9YbUNBTE1QNHRjcXhtIgogIHN5c3RlbV91c2VyOiAicmFiYml0X3N5c3RlbSIKICBzeXN0ZW1fcGFzc3dvcmQ6ICJ4S3l3WjNkc0N2R2FMR0s1aDZuY3RIRDA2bmo3cnhoSSIKCnNkeDoKICBkdW1teXByb2plY3RzOiB8LQogICAgW3sicHJvamVjdElkIjogImM4NzI5ZWFhLTcwNDUtNGRlYi1hMzNmLTEwNzUwM2MxYjA5MCIsInByb2plY3RDb2RlIjogIlBVQi1XQVRFUldJU0UiLCJwcm9qZWN0TmFtZSI6ICJQVUItV0FURVJXSVNFIiwiem9uZSI6ICJJbnRyYW5ldCJ9LAogICAgCXsicHJvamVjdElkIjogIkMwNzY4NjhCLTRBQzMtNEU0MC04Q0YzLTc2NkNCQTc3Rjg0MiIsInByb2plY3RDb2RlIjogIk5FQS1TRU5TT1IiLCJwcm9qZWN0TmFtZSI6ICJORUEtU0VOU09SIiwiem9uZSI6ICJJbnRyYW5ldCIKICAgIAl9LHsicHJvamVjdElkIjogIkMwNzY4NjhCLTRBQzMtNEU0MC04Q0YzLTc2NkNGQTc3Rjg0NiIsInByb2plY3RDb2RlIjogIlBVQkxJU0gtUFVCLTAxIiwicHJvamVjdE5hbWUiOiAiSERCLUhPVVNJTkciLCJ6b25lIjogIkludHJhbmV0IgogICAgCX1dCgpldGNkOgogIGVuYWJsZWQ6IGZhbHNl
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: auth-config
  namespace: {{ include "sense.fullname" . }}
data:
  auth.config.yaml: >-
    Y29nbml0bzoKICBlbmFibGVkOiB0cnVlCiAgY2xpZW50SWQ6ICIxdDNxaW03dmU0N2xvMDRuNmloajFobDZ2bCIKICB1c2VyUG9vbFJlZ2lvbjogImFwLXNvdXRoZWFzdC0xIgogIHVzZXJQb29sSWQ6ICJhcC1zb3V0aGVhc3QtMV83YzdMTkFuSUciICNvcHRpb25hbCBNRkEgdXNlciBwb29sCiAgandrc1VSTDogImh0dHBzOi8vY29nbml0by1pZHAuYXAtc291dGhlYXN0LTEuYW1hem9uYXdzLmNvbS9hcC1zb3V0aGVhc3QtMV83YzdMTkFuSUcvLndlbGwta25vd24vandrcy5qc29uIgogIGp3dER1cmF0aW9uTWluczogNjAgIyBleHRlbmRlZCBmb3IgZWFzaWVyIGRldmVsb3BtZW50CiAgIyB0ZWNocGFzcyBpbnRlZ3JhdGlvbiAtLSBzdGFydAogIHVzZXJwb29sOgogICAgcmVnaW9uOiAiYXAtc291dGhlYXN0LTEiCiAgICBpZDogImFwLXNvdXRoZWFzdC0xX29WSHRuMGZtcCIKICBjbGllbnQ6CiAgICBpZDogIjN0bW92NGlhaDF0Ym1saXNlajljNzM5Y2dhIgogICAgc2VjcmV0OiAiMXVsa2w0c20xcjE5dW1uOGNlNGI2cGhxZDJucHZmYTdpM2RnbGQ0MGU2aWcxZjNubmltNSIKICAjIHRlY2hwYXNzIGludGVncmF0aW9uIC0tIGVuZAoKb2F1dGgyOgogIGVuZHBvaW50OiAibG9naW4uc3RnLnRlY2hwYXNzLmdvdi5zZyIKCndoaXRlbGlzdDoKICBlbWFpbFBhdHRlcm5zOgogICAgLSBecm52ZW5rYXRlc2h3YXJpKCtbYS16QS1aMC05XSspezAsMX1AZ21haWwuY29tJAogICAgLSBebHZsMTAwcCgrW2EtekEtWjAtOV0rKXswLDF9QGdtYWlsLmNvbSQKICAgIC0gXmFhbmJ1KCtbYS16QS1aMC05XSspezAsMX1AcGFsby1pdC5jb20kICMgQWtpbGFuCiAgICAtIF5hbWluKCtbYS16QS1aMC05XSspezAsMX1AcGFsby1pdC5jb20kICMgQWxleAogICAgLSBeYW51anBhbDEyKCtbYS16QS1aMC05XSspezAsMX1AZ21haWwuY29tJCAjIEFudWoKICAgIC0gXmFudWpfcGFsKCtbYS16QS1aMC05XSspezAsMX1AbnNlYXJjaGdsb2JhbC5jb20kICMgQW51agogICAgLSBeYXphZHBhbCgrW2EtekEtWjAtOV0rKXswLDF9QG5zZWFyY2hnbG9iYWwuY29tJCAjIEF6YWQKICAgIC0gXmN0anNjdGpzKCtbYS16QS1aMC05XSspezAsMX1AZ21haWwuY29tJCAjIENsZW1lbnQKICAgIC0gXmJvc2NvX2Zlcm5hbmRvKCtbYS16QS1aMC05XSspezAsMX1AbnNlYXJjaGdsb2JhbC5jb20kICMgQm9zY28KICAgIC0gXmNoZXJpZV9hcmpvbigrW2EtekEtWjAtOV0rKXswLDF9QG5zZWFyY2hnbG9iYWwuY29tJCAjIENoZXJpZQogICAgLSBeLitAaGl2ZS5nb3Yuc2ckCiAgICAtIF4uK0BzaW11bGF0b3IuYW1hem9uc2VzLmNvbSQ=
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: clients-config
  namespace: {{ include "sense.fullname" . }}
data:
  clients.config.yaml: >-
    YXBpczoKICByYWJiaXRtcToKICAgIGhvc3Q6ICJtZGItcm1xLnNlbnNlLWRldi5jb20iCgplbGFzdGljc2VhcmNoOgogIGluZGljZXM6CiAgICBjbGllbnQ6ICJzbnNwLWNsaWVudC1kZXYi
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: topics-config
  namespace: {{ include "sense.fullname" . }}
data:
  topics.config.yaml: >-
    ZWxhc3RpY3NlYXJjaDoKICBpbmRpY2VzOgogICAgZXZlbnRzOiAic25zcC10b3BpY3MtZXZlbnRzLWRldl8qIgogICAgdG9waWNzOiAic25zcC10b3BpY3MtZGV2IgogICAgdGFnY2xvdWQ6ICJzbnNwLXRvcGljcy10YWdjbG91ZC1kZXYiCiAgICB0cmVuZDogICJzbnNwLXRvcGljcy12aWV3LXRyZW5kLWRldiIKICAgIHBheWxvYWQ6ICJzbnNwLXNuaWZmLWxhdGVzdC1wYXlsb2FkLWRldiI=
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: onpremtopic-config
  namespace: {{ include "sense.fullname" . }}
data:
  onpremtopic.config.yaml: >-
    CgpzZHg6CiAgZHVtbXlwcm9qZWN0czogfC0KICAgIFt7InByb2plY3RJZCI6ICJjODcyOWVhYS03MDQ1LTRkZWItYTMzZi0xMDc1MDNjMWIwOTAiLCJwcm9qZWN0Q29kZSI6ICJQVUItV0FURVJXSVNFIiwicHJvamVjdE5hbWUiOiAiUFVCLVdBVEVSV0lTRSIsInpvbmUiOiAiSW50cmFuZXQifSwKICAgIAl7InByb2plY3RJZCI6ICJDMDc2ODY4Qi00QUMzLTRFNDAtOENGMy03NjZDQkE3N0Y4NDIiLCJwcm9qZWN0Q29kZSI6ICJORUEtU0VOU09SIiwicHJvamVjdE5hbWUiOiAiTkVBLVNFTlNPUiIsInpvbmUiOiAiSW50cmFuZXQiCiAgICAJfSx7InByb2plY3RJZCI6ICJDMDc2ODY4Qi00QUMzLTRFNDAtOENGMy03NjZDRkE3N0Y4NDYiLCJwcm9qZWN0Q29kZSI6ICJQVUJMSVNILVBVQi0wMSIsInByb2plY3ROYW1lIjogIkhEQi1IT1VTSU5HIiwiem9uZSI6ICJJbnRyYW5ldCIKICAgIAl9XQ==
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: activity-config
  namespace: {{ include "sense.fullname" . }}
data:
  activity.config.yaml: >-
    ZWxhc3RpY3NlYXJjaDoKICBpbmRpY2VzOgogICAgYWN0aXZpdHk6ICJzbnNwLWFjdGl2aXR5LWRldiI=
type: Opaque