kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.env }}-config
  namespace: {{ include "sense.fullname" . }}
data:
  kube.config.yaml: >-
    bG9nZ2luZzoKICBjb2xvcjogdHJ1ZQoKbW9uZ286CiAgdXNlcjogImFkbWluIgogIHBhc3N3b3JkOiAiNEloUFhvSkRmdlpqaktONFQ1RnhTZFFPVVIzY2gzWTYiCiAgYXBwcGFzc3dvcmQ6ICJaTk5SSTlWeWN2OFRKVlp6RlR5YTR5bnFYRmxRcWoxOSIKICBob3N0OiAiaXAtMTcyLTMxLTE1LTIxLmFwLXNvdXRoZWFzdC0xLmNvbXB1dGUuaW50ZXJuYWwiCgpyZWRpczoKICAgIGhvc3Q6ICJkZXYtcmVkaXMuZ2J4djJrLjAwMDEuYXBzZTEuY2FjaGUuYW1hem9uYXdzLmNvbSIKICAgIHBvcnQ6IDYzNzkKICAgIHBhc3N3b3JkOiAiIgogICAgZGI6IDEKCm5hdHM6CiAgZW5kcG9pbnQ6ICJuYXRzX2NsaWVudDpBQ2VhOGdoYWhiQG5hdHMtY2xpZW50LmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6NDIyMiIKCm9wZW46CiAgdHJhY2luZzoKICAgIGNvbGxlY3Rvci5lbmRwb2ludDogImh0dHA6Ly9qYWVnZXItY29sbGVjdG9yOjE0MjY4L2FwaS90cmFjZXMiCiAgICAKZWxhc3RpY3NlYXJjaDoKICB1cmw6ICJodHRwczovL3ZwYy1kZXYtc2R4LWVzLWtnZmhwdnRmaW8zMm1tbHp4dzIyd2JnaTRpLmFwLXNvdXRoZWFzdC0xLmVzLmFtYXpvbmF3cy5jb20iCiAgaG9zdDogImh0dHBzOi8vdnBjLWRldi1zZHgtZXMta2dmaHB2dGZpbzMybW1senh3MjJ3YmdpNGkuYXAtc291dGhlYXN0LTEuZXMuYW1hem9uYXdzLmNvbSIKICB1c2VybmFtZTogIiIKICBwYXNzd29yZDogIiIKCnJhYmJpdG1xOgogIGhvc3Q6ICJpcC0xNzItMzEtMTUtMjEuYXAtc291dGhlYXN0LTEuY29tcHV0ZS5pbnRlcm5hbCIKICB1c2VybmFtZTogImFkbWluIgogIHBhc3N3b3JkOiAiIVFBWjJ3c3giCgpldGNkOgogIGVuYWJsZWQ6IGZhbHNl
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: auth-config
  namespace: {{ include "sense.fullname" . }}
data:
  auth.config.yaml: >-
    Y29nbml0bzoKICBlbmFibGVkOiB0cnVlCiAgY2xpZW50SWQ6ICIxdDNxaW03dmU0N2xvMDRuNmloajFobDZ2bCIKICB1c2VyUG9vbFJlZ2lvbjogImFwLXNvdXRoZWFzdC0xIgogIHVzZXJQb29sSWQ6ICJhcC1zb3V0aGVhc3QtMV83YzdMTkFuSUciICNvcHRpb25hbCBNRkEgdXNlciBwb29sCiAgandrc1VSTDogImh0dHBzOi8vY29nbml0by1pZHAuYXAtc291dGhlYXN0LTEuYW1hem9uYXdzLmNvbS9hcC1zb3V0aGVhc3QtMV83YzdMTkFuSUcvLndlbGwta25vd24vandrcy5qc29uIgogIGp3dER1cmF0aW9uTWluczogNjAgIyBleHRlbmRlZCBmb3IgZWFzaWVyIGRldmVsb3BtZW50CiAgIyB0ZWNocGFzcyBpbnRlZ3JhdGlvbiAtLSBzdGFydAogIHVzZXJwb29sOgogICAgcmVnaW9uOiAiYXAtc291dGhlYXN0LTEiCiAgICBpZDogImFwLXNvdXRoZWFzdC0xX29WSHRuMGZtcCIKICBjbGllbnQ6CiAgICBpZDogIjN0bW92NGlhaDF0Ym1saXNlajljNzM5Y2dhIgogICAgc2VjcmV0OiAiMXVsa2w0c20xcjE5dW1uOGNlNGI2cGhxZDJucHZmYTdpM2RnbGQ0MGU2aWcxZjNubmltNSIKICAjIHRlY2hwYXNzIGludGVncmF0aW9uIC0tIGVuZAoKb2F1dGgyOgogIGVuZHBvaW50OiAibG9naW4uc3RnLnRlY2hwYXNzLmdvdi5zZyIKCndoaXRlbGlzdDoKICBlbWFpbFBhdHRlcm5zOgogICAgLSBecm52ZW5rYXRlc2h3YXJpKCtbYS16QS1aMC05XSspezAsMX1AZ21haWwuY29tJAogICAgLSBebHZsMTAwcCgrW2EtekEtWjAtOV0rKXswLDF9QGdtYWlsLmNvbSQKICAgIC0gXmFhbmJ1KCtbYS16QS1aMC05XSspezAsMX1AcGFsby1pdC5jb20kICMgQWtpbGFuCiAgICAtIF5hbWluKCtbYS16QS1aMC05XSspezAsMX1AcGFsby1pdC5jb20kICMgQWxleAogICAgLSBeYW51anBhbDEyKCtbYS16QS1aMC05XSspezAsMX1AZ21haWwuY29tJCAjIEFudWoKICAgIC0gXmFudWpfcGFsKCtbYS16QS1aMC05XSspezAsMX1AbnNlYXJjaGdsb2JhbC5jb20kICMgQW51agogICAgLSBeYXphZHBhbCgrW2EtekEtWjAtOV0rKXswLDF9QG5zZWFyY2hnbG9iYWwuY29tJCAjIEF6YWQKICAgIC0gXmN0anNjdGpzKCtbYS16QS1aMC05XSspezAsMX1AZ21haWwuY29tJCAjIENsZW1lbnQKICAgIC0gXmJvc2NvX2Zlcm5hbmRvKCtbYS16QS1aMC05XSspezAsMX1AbnNlYXJjaGdsb2JhbC5jb20kICMgQm9zY28KICAgIC0gXmNoZXJpZV9hcmpvbigrW2EtekEtWjAtOV0rKXswLDF9QG5zZWFyY2hnbG9iYWwuY29tJCAjIENoZXJpZQogICAgLSBeLitAaGl2ZS5nb3Yuc2ckCiAgICAtIF4uK0BzaW11bGF0b3IuYW1hem9uc2VzLmNvbSQ=
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: clients-config
  namespace: {{ include "sense.fullname" . }}
data:
  clients.config.yaml: >-
    YXBpczoKICByYWJiaXRtcToKICAgIGhvc3Q6ICJwYWxvLWl0LmNvbSIKCmVsYXN0aWNzZWFyY2g6CiAgaW5kaWNlczoKICAgIGNsaWVudDogInNuc3AtY2xpZW50LWxvY2FsIg==
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: topics-config
  namespace: {{ include "sense.fullname" . }}
data:
  topics.config.yaml: >-
        ZWxhc3RpY3NlYXJjaDoKICBpbmRpY2VzOgogICAgZXZlbnRzOiAic25zcC0tdG9waWNzLWV2ZW50cy1sb2NhbF8qIgogICAgdG9waWNzOiAic25zcC10b3BpY3MtbG9jYWwiCiAgICB0YWdjbG91ZDogInNuc3AtdG9waWNzLXRhZ2Nsb3VkLWxvY2FsIgogICAgdHJlbmQ6ICAic25zcC10b3BpY3MtdHJlbmQtbG9jYWwiCiAgICBwYXlsb2FkOiAic25zcC1zbmlmZi1sYXRlc3QtcGF5bG9hZC1sb2NhbCI=
type: Opaque
