apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sense.fullname" . }}-portal
  namespace:  {{ include "sense.fullname" . }}
  labels:
   app.kubernetes.io/name: {{ include "sense.fullname" . }}-portal
   app.kubernetes.io/instance: {{ include "sense.fullname" . }}-portal
   app.frontend/group: {{ include "sense.fullname" . }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sense.fullname" . }}-portal
      app.kubernetes.io/instance: {{ include "sense.fullname" . }}-portal
      app.frontend/group: {{ include "sense.fullname" . }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "sense.fullname" . }}-portal
        app.kubernetes.io/instance: {{ include "sense.fullname" . }}-portal
        app.frontend/group: {{ include "sense.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sense.serviceAccountName" . }}
      securityContext: {}
      containers:
        - name:  "{{ include "sense.fullname" . }}-portal"
          securityContext: {}
          image: "{{ .Values.image.repository }}sense-frontend:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 80
            name: public
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: portal
  namespace:  {{ include "sense.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sense.fullname" . }}-portal
    app.kubernetes.io/instance: {{ include "sense.fullname" . }}-portal
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: public
      protocol: TCP
      port: 8080
      targetPort: 80
  selector:
    app.kubernetes.io/name: {{ include "sense.fullname" . }}-portal
    app.kubernetes.io/instance: {{ include "sense.fullname" . }}-portal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sense.fullname" . }}-frontend-auth
  namespace:  {{ include "sense.fullname" . }}
  labels:
   app.kubernetes.io/name: {{ include "sense.fullname" . }}-frontend-auth
   app.kubernetes.io/instance: {{ include "sense.fullname" . }}-frontend-auth
   app.frontend/group: {{ include "sense.fullname" . }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sense.fullname" . }}-frontend-auth
      app.kubernetes.io/instance: {{ include "sense.fullname" . }}-frontend-auth
      app.frontend/group: {{ include "sense.fullname" . }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "sense.fullname" . }}-frontend-auth
        app.kubernetes.io/instance: {{ include "sense.fullname" . }}-frontend-auth
        app.frontend/group: {{ include "sense.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sense.serviceAccountName" . }}
      securityContext: {}
      containers:
        - name:  "{{ include "sense.fullname" . }}-frontend-auth"
          securityContext: {}
          image: "{{ .Values.image.repository }}sense-frontend-auth:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 80
            name: public
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-auth
  namespace:  {{ include "sense.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sense.fullname" . }}-frontend-auth
    app.kubernetes.io/instance: {{ include "sense.fullname" . }}-frontend-auth
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: public
      protocol: TCP
      port: 8080
      targetPort: 80
  selector:
    app.kubernetes.io/name: {{ include "sense.fullname" . }}-frontend-auth
    app.kubernetes.io/instance: {{ include "sense.fullname" . }}-frontend-auth
