{{- range .Values.service.includes }}
{{- $rangeItem := . -}}
{{- with $ }}
{{- if not $rangeItem.disabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $rangeItem.name }}
  namespace:  {{ include "sense.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sense.fullname" . }}-{{ $rangeItem.name }}
    app.kubernetes.io/instance: {{ include "sense.fullname" . }}-{{ $rangeItem.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: public
      protocol: TCP
      port: {{ $rangeItem.publicPort }}
      targetPort: {{ $rangeItem.publicPort }}
    - name: admin
      protocol: TCP
      port: {{ $rangeItem.adminPort }}
      targetPort: {{ $rangeItem.adminPort }}
  selector:
    app.kubernetes.io/name: {{ include "sense.fullname" . }}-{{ $rangeItem.name }}
    app.kubernetes.io/instance: {{ include "sense.fullname" . }}-{{ $rangeItem.name }}
---
{{- end }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  name: ingress-nginx-controller-internal
  namespace: ingress-nginx
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  type: ClusterIP