nginx:
  default: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid;

    # Load dynamic modules. See /usr/share/nginx/README.dynamic.
    include /usr/share/nginx/modules/*.conf;

    events {
        worker_connections 1024;
    }

    http {
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile            on;
        tcp_nopush          on;
        tcp_nodelay         on;
        keepalive_timeout   65;
        types_hash_max_size 2048;
        client_max_body_size 2048;
        client_header_buffer_size 2048;

        gzip              on;
        gzip_http_version 1.0;
        gzip_proxied      any;
        gzip_min_length   500;
        gzip_disable      "MSIE [1-6]\.";
        gzip_types        text/plain text/xml text/css
                          application/javascript
                          application/x-javascript
                          application/json
                          text/comma-separated-values;

        include             /etc/nginx/mime.types;
        default_type        application/octet-stream;

        # Load modular configuration files from the /etc/nginx/conf.d directory.
        # See http://nginx.org/en/docs/ngx_core_module.html#include
        # for more information.
        include /etc/nginx/conf.d/*.conf;
        server_tokens off;

        server {
            listen       80 default_server;
            listen       [::]:80 default_server;
            server_name  _;
            root         /usr/share/nginx/html;

            # Load configuration files for the default server block.
            include /etc/nginx/default.d/*.conf;

            location / {
                # TODO: disable this later
                return 301 https://$host/adex/home;

                # TODO: below will return SPA index always when user approach with wrong URL
                #       SPA can have 404 page
                #try_files $uri $uri/ /adex/index.html =404;
            }

            add_header X-XSS-Protection "1; mode=block";
            add_header X-Content-Type-Options nosniff;
            add_header Content-Security-Policy "default-src 'self' https://*.dcube.cloud/ https://*.demdex.net/ https://cm.everesttech.net/ https://wogadobeanalytics.sc.omtrdc.net/ wss: ; child-src 'self' blob: ; script-src 'self' blob: https://*.dcube.cloud  https://assets.adobedtm.com/ https://assets.developer.tech.gov.sg/ https://*.assets.developer.tech.gov.sg/ https://cdn.jsdelivr.net/npm/@webcomponents/webcomponentsjs@2.6.0/webcomponents-bundle.js https://cdn.jsdelivr.net/npm/whatwg-fetch@3.6.2/dist/fetch.umd.js https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js; img-src 'self' data: https://wogadobeanalytics.sc.omtrdc.net/ https://cm.everesttech.net/ https://dpm.demdex.net/ https://*.onemap.sg https://assets.developer.tech.gov.sg/ https://*.assets.developer.tech.gov.sg/; connect-src 'self' https://*.dcube.cloud https://dpm.demdex.net/ https://assets.developer.tech.gov.sg/ https://*.assets.developer.tech.gov.sg/; style-src 'self' 'unsafe-inline' https://assets.dcube.cloud/fonts/; font-src 'self' data: https://assets.dcube.cloud/fonts/; frame-src 'self' https://wogaa.demdex.net; object-src 'none'; base-uri 'self'; frame-ancestors 'self'; upgrade-insecure-requests";
        }
    }

  module: |
    location ~ /sdx/(.*) {
      return 301 https://$host/adex/$1$is_args$args;
    }
    location /adex/ {
      try_files $uri $uri/ /adex/index.html =404;
    }
