#kind: Deployment

#replicaCount: 1

image:
  repository: 342446142760.dkr.ecr.ap-southeast-1.amazonaws.com/sense_fluentd
  #pullPolicy: IfNotPresent
  pullPolicy: Always
  tag: latest

autoscaling:
  enabled: false

# temp, no metric port for sense image
livenessProbe:
readinessProbe:
