provisionDataStore:
  cassandra: false

storage:
  type: elasticsearch
  elasticsearch:
    host: vpc-dev-adex-es-thhponeikadg6quk2hdoxtx37q.ap-southeast-1.es.amazonaws.com
    port: 443
    scheme: https
    user:
    usePassword: false
    indexPrefix: tracing-dev

collector:
  service:
    zipkin:
      port: 9441
  resources:
    limits:
      memory: 128Mi
      cpu: 0.1

query:
  basePath: /jaeger
  resources:
    limits:
      memory: 128Mi
      cpu: 0.1
agent:
  resources:
    limits:
      memory: 128Mi
      cpu: 0.1
esIndexCleaner:
  enabled: true
  numberOfDays: 7