namespace: monitoring
chartVer: 0.0.4

jaegertracing:
  enabled: true

kube:
  hostname: k8.sense-dev.com
  ingressClassName: external-alb-default

opensearch:
  enabled: true
  hostname: opensearch.sense-dev.com
  ingressClassName: external-alb-default
  openToLocal: true
  vpcEndpoint: vpc-dev-adex-es-thhponeikadg6quk2hdoxtx37q.ap-southeast-1.es.amazonaws.com
  endpoint: https://vpc-dev-adex-es-thhponeikadg6quk2hdoxtx37q.ap-southeast-1.es.amazonaws.com:443

logstash:
  prefix: fluentd-dev