apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  namespace: {{ .Values.namespace | default "sense" }}
data:
  nginx.conf: |
  {{- .Values.nginx.default | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-nginx-config
  namespace: {{ .Values.namespace | default "sense" }}
data:
  nginx-adex.conf: |
  {{- .Values.nginx.module | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-index-config
  namespace: {{ .Values.namespace | default "sense" }}
data:
  index.html: |
  {{- .Values.html.index | nindent 4 }}
---