include:
  - cicd/templates/.common.yml
  - cicd/templates/.helmfile.yml

stages:
  - deploy

variables:
  EKS_CLUSTER_VERSION: $EKS_CLUSTER_VERSION
  DEV_EKS_CLUSTER_NAME: sdx-dev-eks-blue-cluster # TODO


workflow:
  rules:
    - if: '$ENV == "dev/app/chart"'
    - when: never


app-eks-chart:install-cluster-common:
  stage: deploy
  extends: .deploy-helmfile
  variables:
    CHART_NAME: cluster-common
    SCP_SOURCE_FOLDER: sense
    HELM_ENV: dev
    HELMFILE_ROOT: sense/base/cluster-common
  script:
    - !reference [.deploy-helmfile, script]


app-eks-chart:install-ingress-controller:
  stage: deploy
  extends: .deploy-helmfile
  variables:
    CHART_NAME: ingress-controller
    SCP_SOURCE_FOLDER: sense
    HELM_ENV: dev
    HELMFILE_ROOT: sense/base/ingress-controller
  script:
    - !reference [.deploy-helmfile, script]


app-eks-chart:install-monitoring:
  stage: deploy
  extends: .deploy-helmfile
  variables:
    CHART_NAME: monitoring
    SCP_SOURCE_FOLDER: sense
    HELM_ENV: dev
    HELMFILE_ROOT: sense/base/monitoring
  script:
    - !reference [.deploy-helmfile, script]