include:
  - cicd/templates/.terraform.yml


stages:
  - validate
  - plan
  - apply


variables:
  TF_ROOT: sense/terraform


workflow:
  rules:
    - if: '$ENV == "dev"'
    - when: never


app-eks-terraform:validate:
  stage: validate
  extends: .terraform:validate
  environment: $ENV


app-eks-terraform:plan:
  stage: plan
  extends: .terraform:plan
  needs:
    - app-eks-terraform:validate
  environment: $ENV
  script:
    - !reference [.terraform-script:select-workspace, script]
    - export OPTIONS="-var-file=environment/$WORKSPACE/variables.tfvars -target=module.eks_cluster"
    - !reference [.terraform:plan, script]


app-eks-terraform:apply:
  stage: apply
  extends: .terraform:apply
  needs:
    - app-eks-terraform:plan
  environment: $ENV
  script:
    - !reference [.terraform-script:select-workspace, script]
    - export OPTIONS="--auto-approve plan"
    - !reference [.terraform:apply, script]
    - terraform -chdir=$TF_ROOT apply -var-file=environment/$WORKSPACE/variables.tfvars -target=module.eks_post --auto-approve
