include:
  - cicd/templates/.common.yml
  - cicd/templates/.helmfile.yml

stages:
  - deploy

variables:
  K8_VERSION: $K8_VERSION

.gds-account-setup: &gds-account-setup
  variables: {}

.gcc-account-setup: &gcc-account-setup
  variables: {}

workflow:
  rules:
    #    - if: '$ENV == "ami/eks/gds"'
    #      <<: *gds-account-setup
    #    - if: '$ENV == "ami/eks/gcc"'
    #      <<: *gcc-account-setup
    - when: always

app-eks-chart:copy:
  stage: copy
  extends: .helm-builder
  script:
    - |
      export INSTANCE_ID=$DEPLOYMENT_INSTANCE_ID
      export SOURCE_FOLDER=sense
      export SOURCE=$SOURCE_FOLDER/repo.zip
      export DEST=/home/ssm-user/tmp/charts-$CI_COMMIT_REF_SLUG
      export SSH_CMD=$(cat <<EOF
        rm -rf $DEST
        mkdir -p $DEST
        chmod -R 775 $DEST
        chown -R ssm-user:ssm-user $DEST
      EOF
      )
      rm -rf $SOURCE
      zip -r $SOURCE $SOURCE_FOLDER -x "*.terraform*/*" "*.git*/*" "*.idea*/*"
    - !reference [.ssm-ssh-sh, script]
    - !reference [.ssm-scp-sh, script]


app-eks-chart:install-cluster-common:
  extends: .deploy-chart
  variables:
    CHART_NAME: cluster-common
    HELM_ROOT: sense/base
