include:
  - cicd/templates/.common.yml
  - cicd/templates/.helmfile.yml

stages:
  - deploy

workflow:
  rules:
    - if: '$ENV == "dev"'
    - when: never


app-eks-chart:install-cluster-common:
  stage: deploy
  extends: .deploy-helmfile
  variables:
    CHART_NAME: cluster-common
    SCP_SOURCE_FOLDER: sense
    HELM_ENV: dev
    HELMFILE_ROOT: sense/base/cluster-common
  rules:
    - when: manual
  script:
    - !reference [.deploy-helmfile, script]


app-eks-chart:install-ingress-controller:
  stage: deploy
  extends: .deploy-helmfile
  rules:
    - when: manual
  variables:
    CHART_NAME: ingress-controller
    SCP_SOURCE_FOLDER: sense
    HELM_ENV: dev
    HELMFILE_ROOT: sense/base/ingress-controller
  script:
    - !reference [.deploy-helmfile, script]


app-eks-chart:install-monitoring:
  stage: deploy
  extends: .deploy-helmfile
  rules:
    - when: manual
  variables:
    CHART_NAME: monitoring
    SCP_SOURCE_FOLDER: sense
    HELM_ENV: dev
    HELMFILE_ROOT: sense/base/monitoring
  script:
    - !reference [.deploy-helmfile, script]