include:
  - cicd/templates/.common.yml
  - cicd/templates/.helmfile.yml

stages:
  - publish

variables:
  EKS_CLUSTER_VERSION: $EKS_CLUSTER_VERSION


workflow:
  rules:
    - if: '$ENV == "dev/app/chart"'
    - when: never


app-eks-chart:common:
  extends: .publish-chart
  variables:
    CHART_NAME: cluster-common
    HELM_ROOT: sense/base


app-eks-chart:ingress-controller:
  extends: .publish-chart
  variables:
    CHART_NAME: ingress-controller
    HELM_ROOT: sense/base


app-eks-chart:monitoring:
  extends: .publish-chart
  variables:
    CHART_NAME: monitoring
    HELM_ROOT: sense/base


app-eks-chart:sense-backbone:
  extends: .publish-chart
  variables:
    CHART_NAME: sense-backbone
    HELM_ROOT: sense/base


app-eks-chart:sense-frontend-auth:
  extends: .publish-chart
  variables:
    CHART_NAME: sense-frontend-auth
    HELM_ROOT: sense/base


app-eks-chart:sense-frontend-portal:
  extends: .publish-chart
  variables:
    CHART_NAME: sense-frontend-portal
    HELM_ROOT: sense/base


app-eks-chart:sense-backend:
  extends: .publish-chart
  variables:
    CHART_NAME: sense-backend
    HELM_ROOT: sense/base


app-eks-chart:sense-agent:
  extends: .publish-chart
  variables:
    CHART_NAME: sense-agent
    HELM_ROOT: sense/base