include:
  - cicd/templates/.common.yml

stages:
  - setup
  - build

workflow:
  rules:
    - if: '$ENV == "dev"'
    - if: '$ENV == "prod"'
    - when: never


build-packer-ami:
  stage: build
  extends: .awscli-root-builder
  environment: $ENV
  artifacts:
    paths:
      - builder/amazon-eks-ami/*.json
  script:
    - echo "Building AMI for $ENV, AWS_ACCOUNT $AWS_ACCOUNT, K8($EKS_AMI_CLUSTER_VERSION)"
    - |
      if [[ -z $EKS_AMI_CLUSTER_VERSION ]]; then
        echo "EKS_AMI_CLUSTER_VERSION requires, please submit via job variable" && exit 1
      fi
    - chmod +x builder/build.sh
    - |
      builder/build.sh -k $EKS_AMI_CLUSTER_VERSION \
        -a $AWS_ACCOUNT \
        -v $VPC_ID \
        -s $SUBNET_ID \
        -g $SECURITY_GROUP_ID \
        -p $PUBLIC_ACCESS \
        --jq "./jq" \
        --packer "./packer" \
        --repo-tag $AWS_EKS_OPTIMISED_REPO_TAG \
        --working-dir "$(pwd)/builder" \
        --ami-owner $EKS_AMI_OWNER \
        --ami-name $EKS_AMI_NAME
