include:
- project: "WOG/GVT/ADEX/ADEX/sense-eks-deployment"
  ref: "develop"
  file:
  - cicd/templates/.common.yml
- cicd/templates/.common.yml
- cicd/templates/.helmfile.yml
- cicd/templates/.terraform.yml


stages:
#- copy
- validate
- copy
- plan
- apply


workflow:
  rules:
  - if: '$ENV == "dev"'
  - if: '$ENV == "qa"'
  - if: '$ENV == "prod"'
  - if: '$ENV == "intra"'
  - when: never


variables:
  TF_ROOT: environments/sol-$ENV


solace-eks-terraform:copy-artifacts-to-bastion:
  stage: copy
  environment: $ENV
  extends: .awscli-root-builder
  script:
  - |
    echo "SCP build artifacts into Bridge"
    echo "****Folder***"
    echo $CI_PROJECT_DIR
    export EC2_USER=ubuntu
    export DEST=/tmp/solace
    export SCP_SOURCE_FOLDER=$CI_PROJECT_DIR
    export SOURCE=$CI_PROJECT_DIR.zip
    export INSTANCE_ID=$DEPLOYMENT_INSTANCE_ID
  - !reference [.ssm-clean-scp, script]

