include:
  - cicd/templates/.terraform.yml

stages:
  - validate
  - plan
  - apply

variables:
  TF_ROOT:

.gds-account-setup: &gds-account-setup

.gcc-account-setup: &gcc-account-setup


workflow:
  rules:
    - if: '$ENV == "sol/eks/dev"'
      <<: *gds-account-setup
      TF_ROOT: environment/sol-dev
    - when: always
    - if: '$ENV == "sol/eks/qa"'
      <<: *gds-account-setup
      TF_ROOT: environment/sol-qa
    - when: always
    - if: '$ENV == "sol/eks/prod"'
      <<: *gcc-account-setup
      TF_ROOT: environment/sol-prod
    - when: always
    - if: '$ENV == "sol/eks/intra"'
      <<: *gcc-account-setup
      TF_ROOT: environment/sol-intra
    - when: always


sol-eks-terraform:validate:
  stage: validate
  extends: .terraform:validate

#sol-eks-terraform:plan:
#  stage: plan
#  extends: .terraform:plan
#  needs:
#    - sol-eks-terraform:validate
#  script:
#    - echo "TODO!"

#sol-eks-terraform:apply:
#  stage: apply
#  extends: .terraform:apply
#  environment: $ENV
#  needs:
#    - sol-eks-terraform:plan
#  script:
#    - echo "TODO!"