helmBinary: {{ requiredEnv "HELM_BINARY" }}

environments:
  dev:
    values: []

repositories:
  - name: sense-backend
    url: s3://sdx-eks-artifacts/charts/sense-backend

missingFileHandler: Error

releases:
  - name: sense-backend
    namespace: sense
    createNamespace: true
    chart: sense-backend/sense-backend
    version: 0.0.6
    missingFileHandler: Warn
    values:
      - ./values.yaml
      - ../../{{ .Environment.Name }}/sense-backend/values.yaml
      - ../../{{ .Environment.Name }}/sense-backend/config.yaml