helmBinary: {{ requiredEnv "HELM_BINARY" }}

environments:
  dev:
    values:
      - ./values.yaml
      - ../../dev/global.yaml.gotmpl
      - ../../dev/sense-backend/values.yaml

repositories:
  - name: sense-backend
    url: s3://sdx-eks-artifacts/charts/sense-backend

missingFileHandler: Error

releases:
  - name: sense-backend
    namespace: sense
    createNamespace: true
    chart: sense-backend/sense-backend
    version: {{ .Values.chartVer | quote }}
    missingFileHandler: Warn
    values:
      - ./values.yaml
      - ./values.yaml.gotmpl
      - ../../{{ .Environment.Name }}/sense-backend/values.yaml
      - ../../{{ .Environment.Name }}/sense-backend/values.yaml.gotmpl
      - ../../{{ .Environment.Name }}/sense-backend/config.yaml