component: backend

enabled: true

hostname:
  internal:
  external:

replicas: 1

image:
  repository:
  tag: latest
  pullPolicy: IfNotPresent

podAnnotations: {}

podSecurityContext: {}

containerSecurityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  privileged: false
  runAsNonRoot: true
  runAsUser: 10001 # appuser
  capabilities:
    drop:
    - ALL

resources:
  requests:
    memory: "64Mi"
    cpu: "0.1"
  limits:
    memory: "256Mi"
    cpu: "0.2"

internal:
  ingressClassName: internal-nlb-default
external:
  ingressClassName: external-alb-default

autoscaling:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

healthcheck:
  enabled: true
  port: 7171
  livenessProbe:
    exec:
      command:
        - "/go/bin/service"
        - "-ping=true"
    failureThreshold: 3
    periodSeconds: 30
  readinessProbe:
    httpGet:
      path: /diagnostics/healthcheck
      port: healthcheck
    failureThreshold: 3
    periodSeconds: 30

nodeSelector: {}
tolerations: []
affinity: {}

# base configuration will be applied to all env
base:
  envs: []
  volumes:
    - name: default-config
      configMap:
        name: default-config
  mounts:
    - name: default-config
      readOnly: true
      mountPath: /etc/sense/conf/default.config.yaml
      subPath: default.config.yaml

# common configuration will be used to define commons in specific env
commons:
  envs: []
  volumes: []
  mounts: []


serviceAccount:
  name: sense-backend

secrets:
  commons: []
  services: []

ingress:
  certSecret:

certs: []

# ----- micro-service configs -----
deployments:
  # ----- auth -----
  auth:
    imageName: sense_auth
    imageTag:
    adminPort: 9090
    publicPort: 8080
    nodeSelector: {}
    tolerations: []
    affinity: {}
    autoscaling: {}
    resources: {}
    env: []
    volumes: []
    mounts: []
  # ----- iam -----
  iam:
    imageName: sense_iam
    imageTag:
    adminPort: 9091
    publicPort: 8081
    nodeSelector: {}
    tolerations: []
    affinity: {}
    autoscaling: {}
    resources: {}
    env: []
    volumes: []
    mounts: []
  # ----- topics -----
  topics:
    imageName: sense_topics
    imageTag:
    adminPort: 9092
    publicPort: 8082
    nodeSelector: {}
    tolerations: []
    affinity: {}
    autoscaling: {}
    resources: {}
    env: []
    volumes: []
    mounts: []
  # ----- policy -----
  policy:
    imageName: sense_policy
    imageTag:
    adminPort: 9093
    publicPort: 8083
    nodeSelector: {}
    tolerations: []
    affinity: {}
    autoscaling: {}
    resources: {}
    env: []
    volumes: []
    mounts: []
  # ----- role -----
  role:
    imageName: sense_role
    imageTag:
    adminPort: 9094
    publicPort: 8084
    nodeSelector: {}
    tolerations: []
    affinity: {}
    autoscaling: {}
    resources: {}
    env: []
    volumes: []
    mounts: []
  # ----- client -----
  client:
    imageName: sense_client
    imageTag:
    adminPort: 9095
    publicPort: 8085
    nodeSelector: {}
    tolerations: []
    affinity: {}
    autoscaling: {}
    resources: {}
    env: []
    volumes: []
    mounts: []
  # ----- activity -----
  activity:
    imageName: sense_activity
    imageTag:
    adminPort: 9097
    publicPort: 8087
    nodeSelector: {}
    tolerations: []
    affinity: {}
    autoscaling: {}
    resources: {}
    env: []
    volumes: []
    mounts: []
  # ----- subscription -----
  subscription:
    imageName: sense_subscription
    imageTag:
    adminPort: 9098
    publicPort: 8088
    nodeSelector: {}
    tolerations: []
    affinity: {}
    autoscaling: {}
    resources: {}
    env: []
    volumes: []
    mounts: []
  # ----- lookup -----
  lookup:
    imageName: sense_lookup
    imageTag:
    adminPort: 9999
    publicPort: 8999
    nodeSelector: {}
    tolerations: []
    affinity: {}
    autoscaling: {}
    resources: {}
  # ----- message -----
  message:
    imageName: sense_message
    imageTag:
    adminPort: 9100
    publicPort: 8100
    nodeSelector: {}
    tolerations: []
    affinity: {}
    autoscaling: {}
    resources: {}
    env: []
    volumes: []
    mounts: []
  # ----- notification -----
  notification:
    imageName: sense_notification
    imageTag:
    adminPort: 9101
    publicPort: 8101
    nodeSelector: {}
    tolerations: []
    affinity: {}
    autoscaling: {}
    resources: {}
    env: []
    volumes: []
    mounts: []
  # ----- adaptor -----
  adaptor:
    imageName: sense_adaptor
    imageTag:
    adminPort: 9190
    publicPort: 8180
    nodeSelector: {}
    tolerations: []
    affinity: {}
    autoscaling: {}
    resources: {}
    env: []
    volumes: []
    mounts: []
  # ----- appsettings -----
  appsettings:
    imageName: sense_appsettings
    imageTag:
    adminPort: 9192
    publicPort: 8182
    nodeSelector: {}
    tolerations: []
    affinity: {}
    autoscaling: {}
    resources: {}
    env: []
    volumes: []
    mounts: []
  # ----- metric -----
  metric:
    imageName: sense_metric
    imageTag:
    adminPort: 9191
    publicPort: 8181
    nodeSelector: {}
    tolerations: []
    affinity: {}
    autoscaling: {}
    resources: {}
    env: []
    volumes: []
    mounts: []


cronJob:
  enabled: true
  jobs:
    sense-cron-jobs-daily:
      name: sense-cron-jobs-daily
      imageName: sense_cron_jobs
      schedule: "0 16 * * *"
      concurrencyPolicy: Forbid
      containerName: cron-jobs-daily-midnight-sgt
      containerArgs: []
      resources:
        requests:
          memory: "25Mi"
        limits:
          memory: "50Mi"
    sense-cron-jobs-every-thirty-mins:
      name: sense-cron-jobs-every-thirty-mins
      imageName: sense_cron_jobs
      schedule: "*/30 * * * *"
      concurrencyPolicy: Forbid
      containerName: cron-jobs-every-thirty-mins
      containerArgs: []
      resources:
        requests:
          memory: "25Mi"
        limits:
          memory: "50Mi"
